/* eslint-disable */
/**
 * Auto-generated by tools/sync-meals-legacy.mjs
 * Source: legacy/refeicoes.html
 * Generated at: 2026-03-04T20:09:22.921Z
 */

export const LEGACY_MEALS_HTML = `<!-- ============================================= -->
    <!-- SEÇÃO: AMBIENT BACKGROUND                     -->
    <!-- ============================================= -->
    <div class="ambient-bg" aria-hidden="true">
        <div class="ambient-orb ambient-orb--1"></div>
        <div class="ambient-orb ambient-orb--2"></div>
        <div class="ambient-orb ambient-orb--3"></div>
    </div>
    <div class="noise-overlay" aria-hidden="true"></div>

    <!-- SVG Defs for gradients -->
    <svg width="0" height="0" style="position:absolute" aria-hidden="true">
        <defs>
            <linearGradient id="kcalGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stop-color="#10b981" />
                <stop offset="100%" stop-color="#34d399" />
            </linearGradient>
            <linearGradient id="proteinGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stop-color="#10b981" />
                <stop offset="100%" stop-color="#34d399" />
            </linearGradient>
            <linearGradient id="carbGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stop-color="#f4a261" />
                <stop offset="100%" stop-color="#f0c27f" />
            </linearGradient>
            <linearGradient id="fatGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stop-color="#7c6df0" />
                <stop offset="100%" stop-color="#a78bfa" />
            </linearGradient>
        </defs>
    </svg>

    <!-- ============================================= -->
    <!-- SEÇÃO: DASHBOARD PRINCIPAL                    -->
    <!-- ============================================= -->
    <main class="dashboard-section" role="main">

        <!-- ============================================= -->
        <!-- SEÇÃO: HEADER                                 -->
        <!-- ============================================= -->
        <header class="section-header">
            <div class="section-header__top">
                <div class="section-header__left">
                    <div class="section-header__icon" aria-hidden="true">
                        <svg viewBox="0 0 24 24">
                            <path d="M18 8h1a4 4 0 0 1 0 8h-1"/>
                            <path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/>
                            <line x1="6" y1="1" x2="6" y2="4"/>
                            <line x1="10" y1="1" x2="10" y2="4"/>
                            <line x1="14" y1="1" x2="14" y2="4"/>
                        </svg>
                    </div>
                    <div class="section-header__title-group">
                        <span class="section-header__label">Protocolo Nutricional</span>
                        <h1 class="section-header__title">Plano Alimentar Diário</h1>
                    </div>
                </div>
                <div class="section-header__right">
                    <nav class="day-selector" aria-label="Seletor de dia da semana">
                        <button class="day-selector__btn" data-day="0" aria-label="Segunda-feira">S</button>
                        <button class="day-selector__btn" data-day="1" aria-label="Terça-feira">T</button>
                        <button class="day-selector__btn day-selector__btn--active" data-day="2" aria-label="Quarta-feira">Q</button>
                        <button class="day-selector__btn" data-day="3" aria-label="Quinta-feira">Q</button>
                        <button class="day-selector__btn" data-day="4" aria-label="Sexta-feira">S</button>
                        <button class="day-selector__btn" data-day="5" aria-label="Sábado">S</button>
                        <button class="day-selector__btn" data-day="6" aria-label="Domingo">D</button>
                    </nav>
                </div>
            </div>
        </header>

        <!-- ============================================= -->
        <!-- SEÇÃO: TOTAIS DIÁRIOS                         -->
        <!-- ============================================= -->
        <section class="daily-totals" aria-label="Resumo de macros do dia">
            <div class="daily-totals__header">
                <div class="daily-totals__title">
                    <span class="daily-totals__title-text">Resumo do Dia</span>
                    <span class="daily-totals__badge">
                        <span class="daily-totals__badge-dot" aria-hidden="true"></span>
                        Dia Ativo
                    </span>
                </div>
                <span class="daily-totals__progress-label">4 de 4 refeições planejadas</span>
            </div>

            <div class="daily-totals__grid">
                <!-- Total Calorias -->
                <div class="total-stat total-stat--kcal">
                    <div class="total-stat__visual">
                        <div class="calorie-ring-container">
                            <svg viewBox="0 0 80 80" aria-hidden="true">
                                <circle class="calorie-ring__bg" cx="40" cy="40" r="34" />
                                <circle class="calorie-ring__fill" cx="40" cy="40" r="34"
                                    stroke-dasharray="213.63"
                                    stroke-dashoffset="213.63"
                                    data-target="21.36" />
                            </svg>
                            <div class="calorie-ring__center">
                                <div class="calorie-ring__center-value">90%</div>
                                <div class="calorie-ring__center-label">meta</div>
                            </div>
                        </div>
                        <div class="calorie-detail">
                            <span class="calorie-detail__label">Calorias Totais</span>
                            <span class="calorie-detail__value" data-count="3387">0</span>
                            <span class="calorie-detail__sub">kcal / 3.750 meta</span>
                        </div>
                    </div>
                    <div class="calorie-flow" aria-hidden="true">
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 55%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 45%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 70%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 68%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 85%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 90%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--active" style="height: 78%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--inactive" style="height: 30%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--inactive" style="height: 20%"></div>
                        <div class="calorie-flow__bar calorie-flow__bar--inactive" style="height: 15%"></div>
                    </div>
                </div>

                <!-- Proteína -->
                <div class="total-stat">
                    <div class="total-stat__icon-row">
                        <div class="total-stat__icon total-stat__icon--protein" aria-hidden="true">🥩</div>
                        <div class="total-stat__trend total-stat__trend--up">
                            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                                <path d="M5 2L8 5.5H2L5 2Z" fill="#2ec4b6"/>
                            </svg>
                            +5g
                        </div>
                    </div>
                    <div class="total-stat__label">Proteína</div>
                    <div class="total-stat__value-row">
                        <span class="total-stat__value total-stat__value--protein" data-count="158">0</span>
                        <span class="total-stat__unit">g</span>
                    </div>
                    <div class="total-stat__bar">
                        <div class="total-stat__bar-fill total-stat__bar-fill--protein" data-width="79" style="width: 0%"></div>
                    </div>
                    <div class="total-stat__bar-label">
                        <span>0g</span>
                        <span>200g</span>
                    </div>
                </div>

                <!-- Carboidrato -->
                <div class="total-stat">
                    <div class="total-stat__icon-row">
                        <div class="total-stat__icon total-stat__icon--carb" aria-hidden="true">🍚</div>
                        <div class="total-stat__trend total-stat__trend--up">
                            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                                <path d="M5 2L8 5.5H2L5 2Z" fill="#2ec4b6"/>
                            </svg>
                            +12g
                        </div>
                    </div>
                    <div class="total-stat__label">Carboidrato</div>
                    <div class="total-stat__value-row">
                        <span class="total-stat__value total-stat__value--carb" data-count="502">0</span>
                        <span class="total-stat__unit">g</span>
                    </div>
                    <div class="total-stat__bar">
                        <div class="total-stat__bar-fill total-stat__bar-fill--carb" data-width="84" style="width: 0%"></div>
                    </div>
                    <div class="total-stat__bar-label">
                        <span>0g</span>
                        <span>600g</span>
                    </div>
                </div>

                <!-- Gordura -->
                <div class="total-stat">
                    <div class="total-stat__icon-row">
                        <div class="total-stat__icon total-stat__icon--fat" aria-hidden="true">🥑</div>
                        <div class="total-stat__trend total-stat__trend--up">
                            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                                <path d="M5 2L8 5.5H2L5 2Z" fill="#2ec4b6"/>
                            </svg>
                            +3g
                        </div>
                    </div>
                    <div class="total-stat__label">Gordura</div>
                    <div class="total-stat__value-row">
                        <span class="total-stat__value total-stat__value--fat" data-count="83">0</span>
                        <span class="total-stat__unit">g</span>
                    </div>
                    <div class="total-stat__bar">
                        <div class="total-stat__bar-fill total-stat__bar-fill--fat" data-width="69" style="width: 0%"></div>
                    </div>
                    <div class="total-stat__bar-label">
                        <span>0g</span>
                        <span>120g</span>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============================================= -->
        <!-- SEÇÃO: REFEIÇÕES — TIMELINE                   -->
        <!-- ============================================= -->
        <section class="meals-timeline" aria-label="Refeições do dia">

            <!-- Timeline line -->
            <div class="timeline-line" aria-hidden="true">
                <div class="timeline-line__progress" data-progress="100"></div>
            </div>

            <!-- ========== REFEIÇÃO 1: CAFÉ DA MANHÃ ========== -->
            <article class="meal-card" aria-label="Café da Manhã">
                <div class="meal-card__node" aria-hidden="true">
                    <div class="meal-card__dot"></div>
                    <span class="meal-card__time-vertical">07:00</span>
                </div>
                <div class="meal-card__body">
                    <div class="meal-card__accent-stripe" aria-hidden="true"></div>
                    <div class="meal-card__header">
                        <div class="meal-card__header-left">
                            <div class="meal-card__emoji meal-card__emoji--breakfast" aria-hidden="true">☀️</div>
                            <div class="meal-card__title-group">
                                <h3 class="meal-card__name">Café da Manhã</h3>
                                <div class="meal-card__meta">
                                    <span class="meal-card__time">
                                        <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                                        07:00
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="meal-card__header-right">
                            <span class="meal-card__kcal">
                                719
                                <span class="meal-card__kcal-unit">kcal</span>
                            </span>
                            <span class="meal-card__kcal-percent">21.2% do total</span>
                        </div>
                    </div>

                    <div class="meal-card__macros">
                        <div class="macro-pill macro-pill--protein">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--protein" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="25" />
                                </svg>
                                <span class="macro-pill__ring-label">P</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Proteína</span>
                                <span class="macro-pill__value macro-pill__value--protein">
                                    37<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--carb">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--carb" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="55" />
                                </svg>
                                <span class="macro-pill__ring-label">C</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Carboidrato</span>
                                <span class="macro-pill__value macro-pill__value--carb">
                                    102<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--fat">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--fat" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="20" />
                                </svg>
                                <span class="macro-pill__ring-label">G</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Gordura</span>
                                <span class="macro-pill__value macro-pill__value--fat">
                                    18<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="meal-card__distribution">
                        <div class="distribution-bar">
                            <div class="distribution-bar__segment distribution-bar__segment--protein" style="width: 21%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--carb" style="width: 57%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--fat" style="width: 22%"></div>
                        </div>
                        <div class="distribution-labels">
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--protein" aria-hidden="true"></span>
                                P 21%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--carb" aria-hidden="true"></span>
                                C 57%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--fat" aria-hidden="true"></span>
                                G 22%
                            </span>
                        </div>
                    </div>

                    <div class="meal-card__expand-toggle" role="button" tabindex="0" aria-expanded="false" aria-label="Ver alimentos do Café da Manhã">
                        <span class="meal-card__expand-text">Ver alimentos</span>
                        <span class="meal-card__expand-arrow" aria-hidden="true">
                            <svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg>
                        </span>
                    </div>

                    <div class="meal-card__foods" aria-hidden="true">
                        <div class="meal-card__foods-inner">
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥚</span>
                                    <div>
                                        <div class="food-item__name">Ovos mexidos</div>
                                        <div class="food-item__portion">3 unidades (150g)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">18g</span>
                                    <span class="food-item__macro food-item__macro--carb">2g</span>
                                    <span class="food-item__macro food-item__macro--fat">12g</span>
                                    <span class="food-item__macro food-item__macro--kcal">210</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍞</span>
                                    <div>
                                        <div class="food-item__name">Pão integral</div>
                                        <div class="food-item__portion">2 fatias (70g)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">7g</span>
                                    <span class="food-item__macro food-item__macro--carb">28g</span>
                                    <span class="food-item__macro food-item__macro--fat">2g</span>
                                    <span class="food-item__macro food-item__macro--kcal">160</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍌</span>
                                    <div>
                                        <div class="food-item__name">Banana com aveia</div>
                                        <div class="food-item__portion">1 banana + 40g aveia</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">8g</span>
                                    <span class="food-item__macro food-item__macro--carb">55g</span>
                                    <span class="food-item__macro food-item__macro--fat">3g</span>
                                    <span class="food-item__macro food-item__macro--kcal">265</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">☕</span>
                                    <div>
                                        <div class="food-item__name">Café com leite</div>
                                        <div class="food-item__portion">200ml</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">4g</span>
                                    <span class="food-item__macro food-item__macro--carb">17g</span>
                                    <span class="food-item__macro food-item__macro--fat">1g</span>
                                    <span class="food-item__macro food-item__macro--kcal">84</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>

            <!-- ========== REFEIÇÃO 2: LANCHE PRÉ-TREINO ========== -->
            <article class="meal-card" aria-label="Lanche Pré-Treino">
                <div class="meal-card__node" aria-hidden="true">
                    <div class="meal-card__dot"></div>
                    <span class="meal-card__time-vertical">10:30</span>
                </div>
                <div class="meal-card__body">
                    <div class="meal-card__accent-stripe" aria-hidden="true"></div>
                    <div class="meal-card__header">
                        <div class="meal-card__header-left">
                            <div class="meal-card__emoji meal-card__emoji--pre-workout" aria-hidden="true">⚡</div>
                            <div class="meal-card__title-group">
                                <h3 class="meal-card__name">Lanche Pré-Treino</h3>
                                <div class="meal-card__meta">
                                    <span class="meal-card__time">
                                        <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                                        10:30
                                    </span>
                                    <span class="meal-card__tag meal-card__tag--pre-workout">
                                        <span class="meal-card__tag-dot" aria-hidden="true"></span>
                                        Pré-Treino
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="meal-card__header-right">
                            <span class="meal-card__kcal">
                                890
                                <span class="meal-card__kcal-unit">kcal</span>
                            </span>
                            <span class="meal-card__kcal-percent">26.3% do total</span>
                        </div>
                    </div>

                    <div class="meal-card__macros">
                        <div class="macro-pill macro-pill--protein">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--protein" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="22" />
                                </svg>
                                <span class="macro-pill__ring-label">P</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Proteína</span>
                                <span class="macro-pill__value macro-pill__value--protein">
                                    42<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--carb">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--carb" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="58" />
                                </svg>
                                <span class="macro-pill__ring-label">C</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Carboidrato</span>
                                <span class="macro-pill__value macro-pill__value--carb">
                                    138<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--fat">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--fat" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="20" />
                                </svg>
                                <span class="macro-pill__ring-label">G</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Gordura</span>
                                <span class="macro-pill__value macro-pill__value--fat">
                                    20<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="meal-card__distribution">
                        <div class="distribution-bar">
                            <div class="distribution-bar__segment distribution-bar__segment--protein" style="width: 19%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--carb" style="width: 62%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--fat" style="width: 19%"></div>
                        </div>
                        <div class="distribution-labels">
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--protein" aria-hidden="true"></span>
                                P 19%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--carb" aria-hidden="true"></span>
                                C 62%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--fat" aria-hidden="true"></span>
                                G 19%
                            </span>
                        </div>
                    </div>

                    <div class="meal-card__expand-toggle" role="button" tabindex="0" aria-expanded="false" aria-label="Ver alimentos do Lanche Pré-Treino">
                        <span class="meal-card__expand-text">Ver alimentos</span>
                        <span class="meal-card__expand-arrow" aria-hidden="true">
                            <svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg>
                        </span>
                    </div>

                    <div class="meal-card__foods" aria-hidden="true">
                        <div class="meal-card__foods-inner">
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍠</span>
                                    <div>
                                        <div class="food-item__name">Batata doce</div>
                                        <div class="food-item__portion">300g cozida</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">4g</span>
                                    <span class="food-item__macro food-item__macro--carb">62g</span>
                                    <span class="food-item__macro food-item__macro--fat">0g</span>
                                    <span class="food-item__macro food-item__macro--kcal">270</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍗</span>
                                    <div>
                                        <div class="food-item__name">Frango grelhado</div>
                                        <div class="food-item__portion">150g peito</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">35g</span>
                                    <span class="food-item__macro food-item__macro--carb">0g</span>
                                    <span class="food-item__macro food-item__macro--fat">4g</span>
                                    <span class="food-item__macro food-item__macro--kcal">180</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍚</span>
                                    <div>
                                        <div class="food-item__name">Arroz branco</div>
                                        <div class="food-item__portion">200g cozido</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">3g</span>
                                    <span class="food-item__macro food-item__macro--carb">56g</span>
                                    <span class="food-item__macro food-item__macro--fat">1g</span>
                                    <span class="food-item__macro food-item__macro--kcal">260</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥜</span>
                                    <div>
                                        <div class="food-item__name">Pasta de amendoim</div>
                                        <div class="food-item__portion">25g</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">0g</span>
                                    <span class="food-item__macro food-item__macro--carb">20g</span>
                                    <span class="food-item__macro food-item__macro--fat">15g</span>
                                    <span class="food-item__macro food-item__macro--kcal">180</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>

            <!-- ========== REFEIÇÃO 3: ALMOÇO PÓS-TREINO ========== -->
            <article class="meal-card" aria-label="Almoço Pós-Treino">
                <div class="meal-card__node" aria-hidden="true">
                    <div class="meal-card__dot"></div>
                    <span class="meal-card__time-vertical">13:00</span>
                </div>
                <div class="meal-card__body">
                    <div class="meal-card__accent-stripe" aria-hidden="true"></div>
                    <div class="meal-card__header">
                        <div class="meal-card__header-left">
                            <div class="meal-card__emoji meal-card__emoji--post-workout" aria-hidden="true">💪</div>
                            <div class="meal-card__title-group">
                                <h3 class="meal-card__name">Almoço Pós-Treino</h3>
                                <div class="meal-card__meta">
                                    <span class="meal-card__time">
                                        <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                                        13:00
                                    </span>
                                    <span class="meal-card__tag meal-card__tag--post-workout">
                                        <span class="meal-card__tag-dot" aria-hidden="true"></span>
                                        Pós-Treino
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="meal-card__header-right">
                            <span class="meal-card__kcal">
                                1.059
                                <span class="meal-card__kcal-unit">kcal</span>
                            </span>
                            <span class="meal-card__kcal-percent">31.3% do total</span>
                        </div>
                    </div>

                    <div class="meal-card__macros">
                        <div class="macro-pill macro-pill--protein">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--protein" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="28" />
                                </svg>
                                <span class="macro-pill__ring-label">P</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Proteína</span>
                                <span class="macro-pill__value macro-pill__value--protein">
                                    52<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--carb">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--carb" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="52" />
                                </svg>
                                <span class="macro-pill__ring-label">C</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Carboidrato</span>
                                <span class="macro-pill__value macro-pill__value--carb">
                                    152<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--fat">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--fat" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="20" />
                                </svg>
                                <span class="macro-pill__ring-label">G</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Gordura</span>
                                <span class="macro-pill__value macro-pill__value--fat">
                                    25<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="meal-card__distribution">
                        <div class="distribution-bar">
                            <div class="distribution-bar__segment distribution-bar__segment--protein" style="width: 20%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--carb" style="width: 57%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--fat" style="width: 23%"></div>
                        </div>
                        <div class="distribution-labels">
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--protein" aria-hidden="true"></span>
                                P 20%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--carb" aria-hidden="true"></span>
                                C 57%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--fat" aria-hidden="true"></span>
                                G 23%
                            </span>
                        </div>
                    </div>

                    <div class="meal-card__expand-toggle" role="button" tabindex="0" aria-expanded="false" aria-label="Ver alimentos do Almoço Pós-Treino">
                        <span class="meal-card__expand-text">Ver alimentos</span>
                        <span class="meal-card__expand-arrow" aria-hidden="true">
                            <svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg>
                        </span>
                    </div>

                    <div class="meal-card__foods" aria-hidden="true">
                        <div class="meal-card__foods-inner">
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥩</span>
                                    <div>
                                        <div class="food-item__name">Carne moída magra</div>
                                        <div class="food-item__portion">200g (patinho)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">40g</span>
                                    <span class="food-item__macro food-item__macro--carb">0g</span>
                                    <span class="food-item__macro food-item__macro--fat">14g</span>
                                    <span class="food-item__macro food-item__macro--kcal">280</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍚</span>
                                    <div>
                                        <div class="food-item__name">Arroz branco</div>
                                        <div class="food-item__portion">300g cozido</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">5g</span>
                                    <span class="food-item__macro food-item__macro--carb">84g</span>
                                    <span class="food-item__macro food-item__macro--fat">1g</span>
                                    <span class="food-item__macro food-item__macro--kcal">390</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🫘</span>
                                    <div>
                                        <div class="food-item__name">Feijão carioca</div>
                                        <div class="food-item__portion">150g cozido</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">5g</span>
                                    <span class="food-item__macro food-item__macro--carb">38g</span>
                                    <span class="food-item__macro food-item__macro--fat">1g</span>
                                    <span class="food-item__macro food-item__macro--kcal">145</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥗</span>
                                    <div>
                                        <div class="food-item__name">Salada verde c/ azeite</div>
                                        <div class="food-item__portion">Porção + 10ml azeite</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">2g</span>
                                    <span class="food-item__macro food-item__macro--carb">6g</span>
                                    <span class="food-item__macro food-item__macro--fat">9g</span>
                                    <span class="food-item__macro food-item__macro--kcal">105</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🧃</span>
                                    <div>
                                        <div class="food-item__name">Suco de laranja natural</div>
                                        <div class="food-item__portion">300ml</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">0g</span>
                                    <span class="food-item__macro food-item__macro--carb">24g</span>
                                    <span class="food-item__macro food-item__macro--fat">0g</span>
                                    <span class="food-item__macro food-item__macro--kcal">139</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>

            <!-- ========== REFEIÇÃO 4: LANCHE DA TARDE ========== -->
            <article class="meal-card" aria-label="Lanche da Tarde">
                <div class="meal-card__node" aria-hidden="true">
                    <div class="meal-card__dot"></div>
                    <span class="meal-card__time-vertical">16:30</span>
                </div>
                <div class="meal-card__body">
                    <div class="meal-card__accent-stripe" aria-hidden="true"></div>
                    <div class="meal-card__header">
                        <div class="meal-card__header-left">
                            <div class="meal-card__emoji meal-card__emoji--snack" aria-hidden="true">🍊</div>
                            <div class="meal-card__title-group">
                                <h3 class="meal-card__name">Lanche da Tarde</h3>
                                <div class="meal-card__meta">
                                    <span class="meal-card__time">
                                        <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                                        16:30
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="meal-card__header-right">
                            <span class="meal-card__kcal">
                                719
                                <span class="meal-card__kcal-unit">kcal</span>
                            </span>
                            <span class="meal-card__kcal-percent">21.2% do total</span>
                        </div>
                    </div>

                    <div class="meal-card__macros">
                        <div class="macro-pill macro-pill--protein">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--protein" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="24" />
                                </svg>
                                <span class="macro-pill__ring-label">P</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Proteína</span>
                                <span class="macro-pill__value macro-pill__value--protein">
                                    27<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--carb">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--carb" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="60" />
                                </svg>
                                <span class="macro-pill__ring-label">C</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Carboidrato</span>
                                <span class="macro-pill__value macro-pill__value--carb">
                                    110<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                        <div class="macro-pill macro-pill--fat">
                            <div class="macro-pill__ring">
                                <svg viewBox="0 0 42 42" aria-hidden="true">
                                    <circle class="macro-pill__ring-bg" cx="21" cy="21" r="17" />
                                    <circle class="macro-pill__ring-fill macro-pill__ring-fill--fat" cx="21" cy="21" r="17"
                                        stroke-dasharray="106.81"
                                        stroke-dashoffset="106.81"
                                        data-target-percent="25" />
                                </svg>
                                <span class="macro-pill__ring-label">G</span>
                            </div>
                            <div class="macro-pill__info">
                                <span class="macro-pill__name">Gordura</span>
                                <span class="macro-pill__value macro-pill__value--fat">
                                    20<span class="macro-pill__value-unit">g</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="meal-card__distribution">
                        <div class="distribution-bar">
                            <div class="distribution-bar__segment distribution-bar__segment--protein" style="width: 15%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--carb" style="width: 61%"></div>
                            <div class="distribution-bar__segment distribution-bar__segment--fat" style="width: 24%"></div>
                        </div>
                        <div class="distribution-labels">
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--protein" aria-hidden="true"></span>
                                P 15%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--carb" aria-hidden="true"></span>
                                C 61%
                            </span>
                            <span class="distribution-label">
                                <span class="distribution-label__dot distribution-label__dot--fat" aria-hidden="true"></span>
                                G 24%
                            </span>
                        </div>
                    </div>

                    <div class="meal-card__expand-toggle" role="button" tabindex="0" aria-expanded="false" aria-label="Ver alimentos do Lanche da Tarde">
                        <span class="meal-card__expand-text">Ver alimentos</span>
                        <span class="meal-card__expand-arrow" aria-hidden="true">
                            <svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg>
                        </span>
                    </div>

                    <div class="meal-card__foods" aria-hidden="true">
                        <div class="meal-card__foods-inner">
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🧀</span>
                                    <div>
                                        <div class="food-item__name">Tapioca com queijo</div>
                                        <div class="food-item__portion">2 unidades (goma 60g + queijo 40g)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">12g</span>
                                    <span class="food-item__macro food-item__macro--carb">52g</span>
                                    <span class="food-item__macro food-item__macro--fat">10g</span>
                                    <span class="food-item__macro food-item__macro--kcal">340</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥛</span>
                                    <div>
                                        <div class="food-item__name">Whey Protein com leite</div>
                                        <div class="food-item__portion">30g whey + 200ml leite</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">30g</span>
                                    <span class="food-item__macro food-item__macro--carb">15g</span>
                                    <span class="food-item__macro food-item__macro--fat">5g</span>
                                    <span class="food-item__macro food-item__macro--kcal">220</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🍇</span>
                                    <div>
                                        <div class="food-item__name">Mix de frutas</div>
                                        <div class="food-item__portion">Manga, uva e maçã (200g)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">1g</span>
                                    <span class="food-item__macro food-item__macro--carb">35g</span>
                                    <span class="food-item__macro food-item__macro--fat">0g</span>
                                    <span class="food-item__macro food-item__macro--kcal">120</span>
                                </div>
                            </div>
                            <div class="food-item">
                                <div class="food-item__left">
                                    <span class="food-item__icon">🥜</span>
                                    <div>
                                        <div class="food-item__name">Castanha de caju</div>
                                        <div class="food-item__portion">15g (10 unidades)</div>
                                    </div>
                                </div>
                                <div class="food-item__right">
                                    <span class="food-item__macro food-item__macro--protein">3g</span>
                                    <span class="food-item__macro food-item__macro--carb">4g</span>
                                    <span class="food-item__macro food-item__macro--fat">7g</span>
                                    <span class="food-item__macro food-item__macro--kcal">85</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>

        </section>

    </main>

    <!-- ============================================= -->
    <!-- SEÇÃO: JAVASCRIPT — INTERAÇÕES E ANIMAÇÕES    -->
    <!-- ============================================= -->`;

export const LEGACY_MEALS_SCRIPT = `// ============================================= //
        // SEÇÃO: INICIALIZAÇÃO                          //
        // ============================================= //
        document.addEventListener('DOMContentLoaded', function() {
            initCountUpAnimations();
            initProgressBars();
            initMacroRings();
            initCalorieRing();
            initTimelineProgress();
            initExpandToggles();
            initDaySelector();
            initIntersectionObserver();
        });

        // ============================================= //
        // SEÇÃO: COUNT UP — ANIMAÇÃO DE NÚMEROS         //
        // ============================================= //
        function initCountUpAnimations() {
            try {
                var elements = document.querySelectorAll('[data-count]');
                elements.forEach(function(el) {
                    var target = parseInt(el.getAttribute('data-count'), 10);
                    if (isNaN(target) || target <= 0) {
                        el.textContent = '0';
                        return;
                    }
                    animateCount(el, 0, target, 1800);
                });
            } catch (error) {
                console.error('Erro na animação de contagem:', error);
            }
        }

        function animateCount(element, start, end, duration) {
            var startTime = null;
            var range = end - start;

            function step(timestamp) {
                if (!startTime) startTime = timestamp;
                var progress = Math.min((timestamp - startTime) / duration, 1);
                var eased = easeOutExpo(progress);
                var current = Math.floor(start + range * eased);

                if (end >= 1000) {
                    element.textContent = current.toLocaleString('pt-BR');
                } else {
                    element.textContent = current;
                }

                if (progress < 1) {
                    requestAnimationFrame(step);
                } else {
                    if (end >= 1000) {
                        element.textContent = end.toLocaleString('pt-BR');
                    } else {
                        element.textContent = end;
                    }
                }
            }

            requestAnimationFrame(step);
        }

        function easeOutExpo(x) {
            return x === 1 ? 1 : 1 - Math.pow(2, -10 * x);
        }

        // ============================================= //
        // SEÇÃO: PROGRESS BARS — BARRAS DE PROGRESSO    //
        // ============================================= //
        function initProgressBars() {
            try {
                setTimeout(function() {
                    var bars = document.querySelectorAll('.total-stat__bar-fill[data-width]');
                    bars.forEach(function(bar) {
                        var targetWidth = bar.getAttribute('data-width');
                        bar.style.width = targetWidth + '%';
                    });
                }, 500);
            } catch (error) {
                console.error('Erro nas barras de progresso:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: MACRO RINGS — ANÉIS DE MACRO           //
        // ============================================= //
        function initMacroRings() {
            try {
                setTimeout(function() {
                    var rings = document.querySelectorAll('.macro-pill__ring-fill[data-target-percent]');
                    rings.forEach(function(ring) {
                        var percent = parseFloat(ring.getAttribute('data-target-percent'));
                        var circumference = 2 * Math.PI * 17;
                        var offset = circumference - (circumference * percent / 100);
                        ring.style.strokeDashoffset = offset;
                    });
                }, 600);
            } catch (error) {
                console.error('Erro nos anéis de macro:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: CALORIE RING — ANEL PRINCIPAL          //
        // ============================================= //
        function initCalorieRing() {
            try {
                setTimeout(function() {
                    var ring = document.querySelector('.calorie-ring__fill');
                    if (ring) {
                        var targetOffset = parseFloat(ring.getAttribute('data-target'));
                        ring.style.strokeDashoffset = targetOffset;
                    }
                }, 400);
            } catch (error) {
                console.error('Erro no anel de calorias:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: TIMELINE PROGRESS                      //
        // ============================================= //
        function initTimelineProgress() {
            try {
                setTimeout(function() {
                    var progress = document.querySelector('.timeline-line__progress');
                    if (progress) {
                        var targetHeight = progress.getAttribute('data-progress');
                        progress.style.height = targetHeight + '%';
                    }
                }, 800);
            } catch (error) {
                console.error('Erro no progresso da timeline:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: EXPAND TOGGLES — EXPANDIR ALIMENTOS    //
        // ============================================= //
        function initExpandToggles() {
            try {
                var toggles = document.querySelectorAll('.meal-card__expand-toggle');
                toggles.forEach(function(toggle) {
                    toggle.addEventListener('click', function(e) {
                        e.preventDefault();
                        handleExpandToggle(this);
                    });

                    toggle.addEventListener('keydown', function(e) {
                        if (e.key === 'Enter' || e.key === ' ') {
                            e.preventDefault();
                            handleExpandToggle(this);
                        }
                    });
                });
            } catch (error) {
                console.error('Erro nos toggles de expansão:', error);
            }
        }

        function handleExpandToggle(toggle) {
            try {
                var foodsContainer = toggle.nextElementSibling;
                var isExpanded = toggle.classList.contains('is-expanded');
                var expandText = toggle.querySelector('.meal-card__expand-text');

                if (isExpanded) {
                    toggle.classList.remove('is-expanded');
                    foodsContainer.classList.remove('is-expanded');
                    toggle.setAttribute('aria-expanded', 'false');
                    foodsContainer.setAttribute('aria-hidden', 'true');
                    if (expandText) expandText.textContent = 'Ver alimentos';
                } else {
                    toggle.classList.add('is-expanded');
                    foodsContainer.classList.add('is-expanded');
                    toggle.setAttribute('aria-expanded', 'true');
                    foodsContainer.setAttribute('aria-hidden', 'false');
                    if (expandText) expandText.textContent = 'Ocultar alimentos';
                }
            } catch (error) {
                console.error('Erro ao expandir/recolher:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: DAY SELECTOR — SELETOR DE DIA          //
        // ============================================= //
        function initDaySelector() {
            try {
                var buttons = document.querySelectorAll('.day-selector__btn');
                buttons.forEach(function(btn) {
                    btn.addEventListener('click', function(e) {
                        e.preventDefault();
                        buttons.forEach(function(b) {
                            b.classList.remove('day-selector__btn--active');
                        });
                        this.classList.add('day-selector__btn--active');

                        triggerRefreshAnimation();
                    });
                });
            } catch (error) {
                console.error('Erro no seletor de dia:', error);
            }
        }

        function triggerRefreshAnimation() {
            try {
                var mealCards = document.querySelectorAll('.meal-card');
                mealCards.forEach(function(card, index) {
                    card.style.animation = 'none';
                    card.offsetHeight;
                    card.style.animation = 'mealReveal 0.7s var(--ease-out) ' + (0.1 + index * 0.1) + 's both';
                });

                var countElements = document.querySelectorAll('[data-count]');
                countElements.forEach(function(el) {
                    var target = parseInt(el.getAttribute('data-count'), 10);
                    if (!isNaN(target) && target > 0) {
                        animateCount(el, 0, target, 1200);
                    }
                });

                var bars = document.querySelectorAll('.total-stat__bar-fill[data-width]');
                bars.forEach(function(bar) {
                    bar.style.width = '0%';
                    setTimeout(function() {
                        var targetWidth = bar.getAttribute('data-width');
                        bar.style.width = targetWidth + '%';
                    }, 200);
                });

                var rings = document.querySelectorAll('.macro-pill__ring-fill[data-target-percent]');
                rings.forEach(function(ring) {
                    var circumference = 2 * Math.PI * 17;
                    ring.style.strokeDashoffset = circumference;
                    setTimeout(function() {
                        var percent = parseFloat(ring.getAttribute('data-target-percent'));
                        var offset = circumference - (circumference * percent / 100);
                        ring.style.strokeDashoffset = offset;
                    }, 300);
                });

                var calorieRing = document.querySelector('.calorie-ring__fill');
                if (calorieRing) {
                    calorieRing.style.strokeDashoffset = '213.63';
                    setTimeout(function() {
                        var targetOffset = parseFloat(calorieRing.getAttribute('data-target'));
                        calorieRing.style.strokeDashoffset = targetOffset;
                    }, 300);
                }
            } catch (error) {
                console.error('Erro na animação de refresh:', error);
            }
        }

        // ============================================= //
        // SEÇÃO: INTERSECTION OBSERVER                  //
        // ============================================= //
        function initIntersectionObserver() {
            try {
                if (!('IntersectionObserver' in window)) {
                    return;
                }

                var observer = new IntersectionObserver(function(entries) {
                    entries.forEach(function(entry) {
                        if (entry.isIntersecting) {
                            entry.target.classList.add('is-visible');
                        }
                    });
                }, {
                    threshold: 0.1,
                    rootMargin: '0px 0px -50px 0px'
                });

                var elements = document.querySelectorAll('.meal-card, .daily-totals, .section-header');
                elements.forEach(function(el) {
                    observer.observe(el);
                });
            } catch (error) {
                console.error('Erro no Intersection Observer:', error);
            }
        }`;
/* @deprecated Legacy meals payload kept temporarily for the final cleanup pass. */
