/* eslint-disable */
/**
 * Auto-generated by tools/sync-projection-legacy.mjs
 * Source: legacy/projecao.html
 * Generated at: 2026-03-04T20:09:22.971Z
 */

export const LEGACY_PROJECTION_HTML = `<!-- ============================================= -->
  <!-- BACKGROUND DECORATIVE ELEMENTS               -->
  <!-- ============================================= -->
  <div class="bg-grid" aria-hidden="true"></div>
  <div class="noise-overlay" aria-hidden="true"></div>
  <div class="bg-decor-blob-1" aria-hidden="true"></div>
  <div class="bg-decor-blob-2" aria-hidden="true"></div>
  <div class="celebrate-overlay" id="celebrateOverlay" aria-hidden="true"></div>

  <!-- ============================================= -->
  <!-- CHART TOOLTIP (Global, position:fixed)       -->
  <!-- ============================================= -->
  <div class="chart-tooltip" id="chartTooltip" role="tooltip" aria-live="polite">
    <div class="tooltip-week" id="tooltipWeek">
      <span class="tooltip-week-badge" id="tooltipWeekBadge">Sem. 1</span>
      <span id="tooltipRefeedFlag"></span>
    </div>
    <div class="tooltip-rows" id="tooltipRows"></div>
    <div class="tooltip-progress-bar-wrap">
      <div class="tooltip-progress-label">
        <span>Progresso total</span>
        <span id="tooltipProgressPct">0%</span>
      </div>
      <div class="tooltip-progress-track">
        <div class="tooltip-progress-fill" id="tooltipProgressFill" style="width:0%"></div>
      </div>
    </div>
  </div>

  <!-- ============================================= -->
  <!-- MAIN PAGE WRAPPER                            -->
  <!-- ============================================= -->
  <div class="page-wrapper" style="position:relative;z-index:1;">

    <!-- ============================================= -->
    <!-- SECTION HEADER                              -->
    <!-- ============================================= -->
    <header class="section-header animate-fade-up delay-1" aria-label="Cabeçalho da seção Projeção">
      <div class="section-header-left">
        <div class="section-eyebrow" aria-hidden="true">
          <span class="section-eyebrow-dot"></span>
          Protocolo DietForge — M?dulo 04
        </div>
        <h1 class="section-title">
          Projeção &amp; <span class="highlight">Progresso</span>
        </h1>
        <p class="section-subtitle">
          Se voc? seguir esse protocolo com consist?ncia, veja exatamente como seu corpo vai se transformar 
          semana a semana ao longo das pr?ximas <strong style="color:var(--text-primary)">16 semanas</strong>. 
          Cada ponto no gr?fico — uma promessa — e voc? tem o poder de cumpri-la.
        </p>
      </div>
      <div class="section-header-right">
        <div class="protocol-badge" role="status" aria-label="Tipo de protocolo: Cutting">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
            <path d="M13 17l5-5-5-5M6 17l5-5-5-5"/>
          </svg>
          Cutting
        </div>
        <div class="protocol-badge protocol-badge-realistic" role="status" aria-label="Classificação: Realista">
          <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true">
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="currentColor"/>
            <polyline points="22,4 12,14.01 9,11.01" stroke="currentColor"/>
          </svg>
          Realista
        </div>
      </div>
    </header>

    <!-- ============================================= -->
    <!-- SUMMARY STAT STRIP                          -->
    <!-- ============================================= -->
    <section class="summary-strip" aria-label="Resumo do protocolo">

      <div class="summary-stat animate-fade-up delay-2"
           style="--stat-accent:var(--color-accent); --stat-accent-bg:var(--color-accent-muted);"
           role="group" aria-label="Duração: 16 semanas">
        <div class="summary-stat-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-accent)" stroke-width="2" aria-hidden="true">
            <rect x="3" y="4" width="18" height="18" rx="2"/>
            <line x1="16" y1="2" x2="16" y2="6"/>
            <line x1="8" y1="2" x2="8" y2="6"/>
            <line x1="3" y1="10" x2="21" y2="10"/>
          </svg>
        </div>
        <div class="summary-stat-label">Duração</div>
        <div class="summary-stat-value" id="statWeeks">16</div>
        <div class="summary-stat-sub">semanas de protocolo</div>
      </div>

      <div class="summary-stat animate-fade-up delay-3"
           style="--stat-accent:var(--color-teal); --stat-accent-bg:var(--color-teal-muted);"
           role="group" aria-label="Perda total projetada: 8.5 kg">
        <div class="summary-stat-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-teal)" stroke-width="2" aria-hidden="true">
            <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
            <polyline points="17 6 23 6 23 12"/>
          </svg>
        </div>
        <div class="summary-stat-label">Perda Total</div>
        <div class="summary-stat-value" id="statLoss">?8.5</div>
        <div class="summary-stat-sub"><strong>84.0 kg</strong> — ~75.5 kg</div>
      </div>

      <div class="summary-stat animate-fade-up delay-4"
           style="--stat-accent:var(--color-amber); --stat-accent-bg:var(--color-amber-muted);"
           role="group" aria-label="D?ficit cal?rico di?rio: 598 kcal">
        <div class="summary-stat-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-amber)" stroke-width="2" aria-hidden="true">
            <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>
          </svg>
        </div>
        <div class="summary-stat-label">D?ficit Di?rio</div>
        <div class="summary-stat-value" id="statDeficit">598</div>
        <div class="summary-stat-sub">kcal/dia aplicado</div>
      </div>

      <div class="summary-stat animate-fade-up delay-5"
           style="--stat-accent:var(--color-purple); --stat-accent-bg:var(--color-purple-muted);"
           role="group" aria-label="Velocidade de perda: 0.53 kg por semana">
        <div class="summary-stat-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-purple)" stroke-width="2" aria-hidden="true">
            <circle cx="12" cy="12" r="10"/>
            <polyline points="12 6 12 12 16 14"/>
          </svg>
        </div>
        <div class="summary-stat-label">Velocidade M?dia</div>
        <div class="summary-stat-value" id="statSpeed">~0.53</div>
        <div class="summary-stat-sub">kg/semana de perda</div>
      </div>

      <div class="summary-stat animate-fade-up delay-6"
           style="--stat-accent:#22c55e; --stat-accent-bg:var(--color-green-muted);"
           role="group" aria-label="BF% final projetado: 8.7%">
        <div class="summary-stat-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="#22c55e" stroke-width="2" aria-hidden="true">
            <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/>
            <path d="M8 14s1.5 2 4 2 4-2 4-2"/>
            <line x1="9" y1="9" x2="9.01" y2="9"/>
            <line x1="15" y1="9" x2="15.01" y2="9"/>
          </svg>
        </div>
        <div class="summary-stat-label">BF% Final</div>
        <div class="summary-stat-value" id="statBf">8.7%</div>
        <div class="summary-stat-sub"><strong>18.0%</strong> — ~8.7% gordura</div>
      </div>

    </section>

    <!-- ============================================= -->
    <!-- MAIN PROJECTION CHART                       -->
    <!-- ============================================= -->
    <section class="chart-section animate-fade-up delay-4" aria-label="Gráfico de projeção corporal">
      <div class="section-glow-arc" aria-hidden="true"></div>

      <div class="chart-header">
        <div class="chart-title-group">
          <div class="chart-title">Curva de Transformação Corporal</div>
          <div class="chart-subtitle">Projeção semana a semana com adaptação metabólica — hover para detalhes</div>
        </div>
        <div class="chart-legend" role="list" aria-label="Legenda do gr?fico">
          <div class="legend-item active legend-weight" role="listitem"
               id="legendWeight" onclick="toggleSeries('weight')" tabindex="0"
               aria-label="S?rie Peso Corporal — clique para mostrar/ocultar">
            <span class="legend-dot" style="background:var(--color-accent); box-shadow:0 0 8px rgba(16,185,129,0.5);" aria-hidden="true"></span>
            Peso Corporal
          </div>
          <div class="legend-item active legend-bf" role="listitem"
               id="legendBF" onclick="toggleSeries('bf')" tabindex="0"
               aria-label="S?rie Body Fat% — clique para mostrar/ocultar">
            <span class="legend-dot" style="background:var(--color-teal); box-shadow:0 0 8px rgba(45,212,191,0.4);" aria-hidden="true"></span>
            Body Fat %
          </div>
          <div class="legend-item active legend-lbm" role="listitem"
               id="legendLBM" onclick="toggleSeries('lbm')" tabindex="0"
               aria-label="S?rie Massa Magra — clique para mostrar/ocultar">
            <span class="legend-dot" style="background:var(--color-purple); box-shadow:0 0 8px rgba(168,85,247,0.4);" aria-hidden="true"></span>
            Massa Magra
          </div>
          <div class="legend-item" role="listitem" aria-label="Marcador de semana de refeed">
            <span style="display:inline-flex;align-items:center;gap:4px;" aria-hidden="true">
              <svg width="16" height="10" viewBox="0 0 16 10" aria-hidden="true">
                <line x1="0" y1="5" x2="16" y2="5" stroke="rgba(245,158,11,0.7)" stroke-width="1.5" stroke-dasharray="2,3"/>
              </svg>
            </span>
            Refeed
          </div>
        </div>
      </div>

      <div class="chart-canvas-wrapper" role="img" aria-label="Gráfico de projeção mostrando curvas de peso, gordura corporal e massa magra ao longo de 16 semanas">
        <canvas id="projectionChart"></canvas>
      </div>

      <!-- Week selector pills -->
      <div class="week-selector-wrap" role="group" aria-label="Seletor de semana">
        <!-- Generated by JS -->
      </div>
    </section>

    <!-- ============================================= -->
    <!-- BOTTOM ROW: BEFORE/AFTER + MILESTONES       -->
    <!-- ============================================= -->
    <div class="bottom-row">

      <!-- BEFORE & AFTER CARD -->
      <article class="before-after-card animate-fade-left delay-5" aria-label="Comparação Antes e Depois">
        <div class="card-label">
          <div class="card-label-icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true">
              <path d="M8 3H5a2 2 0 00-2 2v3m18 0V5a2 2 0 00-2-2h-3m0 18h3a2 2 0 002-2v-3M3 16v3a2 2 0 002 2h3" stroke="var(--color-accent)"/>
            </svg>
          </div>
          Comparação Antes &amp; Depois
        </div>

        <div class="before-after-grid">

          <!-- BEFORE COLUMN -->
          <div class="ba-column" role="group" aria-label="Estado atual">
            <div class="ba-column-header">
              <span class="ba-column-badge before" aria-label="Estado: Antes">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                Agora
              </span>
            </div>
            <div class="ba-metric-row highlight-before" role="group" aria-label="Peso atual: 84.0 kg">
              <div class="ba-metric-name">Peso Total</div>
              <div class="ba-metric-value" id="baBeforeWeight">
                84.0<span class="ba-metric-unit">kg</span>
              </div>
              <div class="ba-metric-sub">Peso inicial do protocolo</div>
            </div>
            <div class="ba-metric-row highlight-before" role="group" aria-label="Body fat atual: 18.0%">
              <div class="ba-metric-name">Body Fat</div>
              <div class="ba-metric-value" id="baBeforeBf">
                18.0<span class="ba-metric-unit">%</span>
              </div>
              <div class="ba-metric-sub">15.12 kg de gordura</div>
            </div>
            <div class="ba-metric-row highlight-before" role="group" aria-label="Massa magra atual: 68.9 kg">
              <div class="ba-metric-name">Massa Magra</div>
              <div class="ba-metric-value" id="baBeforeLbm">
                68.9<span class="ba-metric-unit">kg</span>
              </div>
              <div class="ba-metric-sub">M?sculos, ossos, ?rg?os</div>
            </div>
          </div>

          <!-- DIVIDER ARROW -->
          <div class="ba-divider" aria-hidden="true">
            <div class="ba-arrow-line"></div>
            <div class="ba-arrow-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true">
                <line x1="5" y1="12" x2="19" y2="12" stroke="var(--color-accent)"/>
                <polyline points="12,5 19,12 12,19" stroke="var(--color-accent)"/>
              </svg>
            </div>
            <div class="ba-arrow-line"></div>
          </div>

          <!-- AFTER COLUMN -->
          <div class="ba-column" role="group" aria-label="Estado projetado ap?s 16 semanas">
            <div class="ba-column-header">
              <span class="ba-column-badge after" aria-label="Estado: Depois (projetado)">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><polyline points="20,6 9,17 4,12"/></svg>
                Sem. 16
              </span>
            </div>
            <div class="ba-metric-row highlight-after" role="group" aria-label="Peso projetado: 75.5 kg">
              <div class="ba-metric-name">Peso Total</div>
              <div class="ba-metric-value" style="color:var(--color-teal)" id="baAfterWeight">
                75.5<span class="ba-metric-unit" style="color:var(--text-secondary)">kg</span>
              </div>
              <div class="ba-metric-sub" style="color:#22c55e;">
                <strong style="color:#22c55e;">? 8.5 kg perdidos</strong>
              </div>
            </div>
            <div class="ba-metric-row highlight-after" role="group" aria-label="Body fat projetado: 8.7%">
              <div class="ba-metric-name">Body Fat</div>
              <div class="ba-metric-value" style="color:var(--color-teal)" id="baAfterBf">
                8.7<span class="ba-metric-unit" style="color:var(--text-secondary)">%</span>
              </div>
              <div class="ba-metric-sub" style="color:#22c55e;">
                <strong style="color:#22c55e;">? 9.3pp eliminados</strong>
              </div>
            </div>
            <div class="ba-metric-row highlight-after" role="group" aria-label="Massa magra projetada: 68.9 kg">
              <div class="ba-metric-name">Massa Magra</div>
              <div class="ba-metric-value" style="color:var(--color-purple)" id="baAfterLbm">
                68.9<span class="ba-metric-unit" style="color:var(--text-secondary)">kg</span>
              </div>
              <div class="ba-metric-sub" style="color:var(--color-purple);">
                <strong style="color:var(--color-purple);">? 100% preservada</strong>
              </div>
            </div>
          </div>

        </div><!-- /before-after-grid -->

        <!-- Delta summary badges -->
        <div class="ba-delta-grid" role="group" aria-label="Resumo das mudan?as projetadas">

          <div class="ba-delta-item" role="group" aria-label="Gordura eliminada: 6.55 kg">
            <div class="ba-delta-icon" style="background:rgba(16,185,129,0.1)" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-accent)" stroke-width="2.5" aria-hidden="true">
                <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
                <polyline points="17 6 23 6 23 12"/>
              </svg>
            </div>
            <div class="ba-delta-label">Gordura eliminada</div>
            <div class="ba-delta-value" style="color:var(--color-accent);">?6.55<span style="font-size:11px;font-weight:600;color:var(--text-secondary)">kg</span></div>
            <div class="ba-delta-desc">de 15.12 kg — 6.57 kg</div>
          </div>

          <div class="ba-delta-item" role="group" aria-label="M?sculos preservados: 100%">
            <div class="ba-delta-icon" style="background:rgba(168,85,247,0.1)" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-purple)" stroke-width="2.5" aria-hidden="true">
                <path d="M6.5 6.5c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v11c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2v-11z"/>
                <path d="M9 3v3M15 3v3M9 18v3M15 18v3"/>
                <path d="M3 9h3M18 9h3M3 15h3M18 15h3"/>
              </svg>
            </div>
            <div class="ba-delta-label">M?sculo preservado</div>
            <div class="ba-delta-value" style="color:var(--color-purple);">100<span style="font-size:11px;font-weight:600;color:var(--text-secondary)">%</span></div>
            <div class="ba-delta-desc">68.9 kg LBM intacta</div>
          </div>

          <div class="ba-delta-item" role="group" aria-label="Deficit total de 67 mil kcal">
            <div class="ba-delta-icon" style="background:rgba(245,158,11,0.1)" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-amber)" stroke-width="2.5" aria-hidden="true">
                <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>
              </svg>
            </div>
            <div class="ba-delta-label">D?ficit acumulado</div>
            <div class="ba-delta-value" style="color:var(--color-amber);">67k<span style="font-size:11px;font-weight:600;color:var(--text-secondary)">kcal</span></div>
            <div class="ba-delta-desc">598 kcal ? 112 dias</div>
          </div>

        </div>
      </article>

      <!-- MILESTONES TIMELINE -->
      <article class="milestones-card animate-fade-right delay-5" aria-label="Marcos e conquistas do protocolo">
        <div class="card-label" style="margin-bottom:var(--space-5)">
          <div class="card-label-icon" style="background:rgba(45,212,191,0.1);" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-teal)" stroke-width="2.5" aria-hidden="true">
              <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
            </svg>
          </div>
          Marcos &amp; Conquistas
        </div>

        <ol class="milestones-list" aria-label="Lista de marcos do protocolo">

          <li class="milestone-item" role="listitem" onclick="highlightWeek(1)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot reached">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" stroke="currentColor"/></svg>
              </div>
              <div class="milestone-line"></div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 1 — Início</div>
              <div class="milestone-title">Protocolo Ativado</div>
              <div class="milestone-desc">D?ficit de 598 kcal/dia em vigor. Peso: 84.0 kg, BF 18.0%. O corpo começa a responder imediatamente nas primeiras 48h.</div>
              <span class="milestone-tag red">Dia Zero</span>
            </div>
          </li>

          <li class="milestone-item" role="listitem" onclick="highlightWeek(4)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot reached">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><circle cx="12" cy="12" r="10" stroke="currentColor"/><polyline points="12,6 12,12 16,14" stroke="currentColor"/></svg>
              </div>
              <div class="milestone-line"></div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 4 — 1? Refeed</div>
              <div class="milestone-title">Primeiro Ciclo de Refeed</div>
              <div class="milestone-desc">Ap?s 28 dias, refeição de recarga para resetar leptina e manter performance. −2.1 kg acumulado até aqui.</div>
              <span class="milestone-tag amber">Refeed Day</span>
            </div>
          </li>

          <li class="milestone-item" role="listitem" onclick="highlightWeek(6)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot highlight">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="currentColor"/></svg>
              </div>
              <div class="milestone-line"></div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 6 — Queda Vis?vel</div>
              <div class="milestone-title">BF abaixo de 15% 🎯</div>
              <div class="milestone-desc">Marco psicológico importante: a diferença visual começa a ser notada no espelho. Vascularização inicial.</div>
              <span class="milestone-tag teal">Marco Visual</span>
            </div>
          </li>

          <li class="milestone-item" role="listitem" onclick="highlightWeek(8)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot upcoming">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" stroke="currentColor"/></svg>
              </div>
              <div class="milestone-line"></div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 8 — Meio do Protocolo</div>
              <div class="milestone-title">Metade da Jornada — ?4.3 kg</div>
              <div class="milestone-desc">Ponto de inflexão da adaptação metabólica. Segundo ciclo de refeed para reajustar o motor metab?lico.</div>
              <span class="milestone-tag amber">2? Refeed</span>
              <span class="milestone-tag purple" style="margin-left:4px;">Meio do Caminho</span>
            </div>
          </li>

          <li class="milestone-item" role="listitem" onclick="highlightWeek(12)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot upcoming">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><circle cx="12" cy="12" r="10" stroke="currentColor"/><path d="M8.56 2.75c4.37 6.03 6.02 9.42 8.03 17.72m2.54-15.38c-3.72 4.35-8.94 5.66-16.88 5.85m19.5 1.9c-3.5-.93-6.63-.82-8.94 0-2.58.92-5.01 2.86-7.44 6.32" stroke="currentColor"/></svg>
              </div>
              <div class="milestone-line"></div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 12 — Definição</div>
              <div class="milestone-title">BF abaixo de 12% — Athleticamente Definido</div>
              <div class="milestone-desc">Vascularização avançada, separação muscular clara. Abdominais superiores visíveis. Adaptação metabólica máxima.</div>
              <span class="milestone-tag teal">Definição Elite</span>
            </div>
          </li>

          <li class="milestone-item" role="listitem" onclick="highlightWeek(16)">
            <div class="milestone-left" aria-hidden="true">
              <div class="milestone-dot gold">
                <svg viewBox="0 0 24 24" fill="none" stroke-width="2.5" aria-hidden="true"><polygon points="12,2 15.09,8.26 22,9.27 17,14.14 18.18,21.02 12,17.77 5.82,21.02 7,14.14 2,9.27 8.91,8.26" stroke="currentColor"/></svg>
              </div>
            </div>
            <div class="milestone-content">
              <div class="milestone-week">Semana 16 — Conclus?o</div>
              <div class="milestone-title">🏆 Objetivo Alcançado — 75.5 kg / 8.7% BF</div>
              <div class="milestone-desc">Protocolo concluído. 8.5 kg de gordura eliminados, massa magra 100% preservada. Pronto para fase de manutenção ou bulk.</div>
              <span class="milestone-tag amber">Meta Final</span>
            </div>
          </li>

        </ol>
      </article>

    </div><!-- /bottom-row -->

    <!-- ============================================= -->
    <!-- BODY COMPOSITION VISUAL — STACKED BARS      -->
    <!-- ============================================= -->
    <section class="body-comp-card animate-fade-up delay-6" aria-label="Composição corporal detalhada">
      <div class="card-label" style="margin-bottom:var(--space-6)">
        <div class="card-label-icon" style="background:rgba(168,85,247,0.1);" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-purple)" stroke-width="2.5" aria-hidden="true">
            <rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 9h6M9 12h6M9 15h4"/>
          </svg>
        </div>
        Composição Corporal — Antes vs Depois
      </div>
      <div class="body-comp-grid">

        <!-- PESO TOTAL -->
        <div class="body-comp-item" role="group" aria-label="Peso total antes e depois">
          <div class="body-comp-item-header">
            <span class="body-comp-item-label">Peso Total</span>
            <span class="body-comp-item-change down" aria-label="Redução de 10.1%">↓ 10.1%</span>
          </div>
          <div class="body-comp-stacked-bar">
            <div class="stacked-bar-row" role="group" aria-label="Peso antes: 84.0 kg">
              <span class="stacked-bar-label">Antes</span>
              <div class="stacked-bar-track" title="84.0 kg — 100%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, var(--color-accent), #c0182a); width:0%"
                     data-width="100%"
                     aria-label="Barra de peso antes, 100%"></div>
              </div>
              <span class="stacked-bar-value">84.0 kg</span>
            </div>
            <div class="stacked-bar-row" role="group" aria-label="Peso depois: 75.5 kg">
              <span class="stacked-bar-label">Depois</span>
              <div class="stacked-bar-track" title="75.5 kg — 89.9%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, var(--color-teal), #1a8c81); width:0%"
                     data-width="89.9%"
                     aria-label="Barra de peso depois, 89.9% do inicial"></div>
              </div>
              <span class="stacked-bar-value">75.5 kg</span>
            </div>
          </div>
        </div>

        <!-- GORDURA CORPORAL -->
        <div class="body-comp-item" role="group" aria-label="Gordura corporal antes e depois">
          <div class="body-comp-item-header">
            <span class="body-comp-item-label">Massa Gordurosa</span>
            <span class="body-comp-item-change down" aria-label="Redução de 43.4%">↓ 43.4%</span>
          </div>
          <div class="body-comp-stacked-bar">
            <div class="stacked-bar-row" role="group" aria-label="Gordura antes: 15.12 kg">
              <span class="stacked-bar-label">Antes</span>
              <div class="stacked-bar-track" title="15.12 kg — 100%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, #10b981, #047857); width:0%"
                     data-width="100%"
                     aria-label="Barra de gordura antes, 100%"></div>
              </div>
              <span class="stacked-bar-value">15.12 kg</span>
            </div>
            <div class="stacked-bar-row" role="group" aria-label="Gordura depois: 6.57 kg">
              <span class="stacked-bar-label">Depois</span>
              <div class="stacked-bar-track" title="6.57 kg — 56.6%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, #22c55e, #16a34a); width:0%"
                     data-width="56.6%"
                     aria-label="Barra de gordura depois, 56.6% do inicial"></div>
              </div>
              <span class="stacked-bar-value">6.57 kg</span>
            </div>
          </div>
        </div>

        <!-- MASSA MAGRA -->
        <div class="body-comp-item" role="group" aria-label="Massa magra antes e depois">
          <div class="body-comp-item-header">
            <span class="body-comp-item-label">Massa Magra (LBM)</span>
            <span class="body-comp-item-change preserve" aria-label="Preservada 100%">? 100%</span>
          </div>
          <div class="body-comp-stacked-bar">
            <div class="stacked-bar-row" role="group" aria-label="Massa magra antes: 68.9 kg">
              <span class="stacked-bar-label">Antes</span>
              <div class="stacked-bar-track" title="68.9 kg — 100%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, var(--color-purple), #7c3aed); width:0%"
                     data-width="100%"
                     aria-label="Barra de massa magra antes, 100%"></div>
              </div>
              <span class="stacked-bar-value">68.9 kg</span>
            </div>
            <div class="stacked-bar-row" role="group" aria-label="Massa magra depois: 68.93 kg">
              <span class="stacked-bar-label">Depois</span>
              <div class="stacked-bar-track" title="68.93 kg — 100.04%">
                <div class="stacked-bar-fill"
                     style="background: linear-gradient(90deg, var(--color-purple), #7c3aed); width:0%"
                     data-width="100%"
                     aria-label="Barra de massa magra depois, 100%"></div>
              </div>
              <span class="stacked-bar-value">68.9 kg</span>
            </div>
          </div>
        </div>

      </div>
    </section>

    <!-- ============================================= -->
    <!-- INFO ROW — 3 CARDS                          -->
    <!-- ============================================= -->
    <div class="info-row">

      <!-- ADAPTAÃ‡ÃƒO METABÃ“LICA -->
      <div class="info-card animate-fade-up delay-6" role="complementary" aria-label="Informação sobre adaptação metabólica">
        <div class="info-card-icon-wrap" style="background:rgba(245,158,11,0.1)" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-amber)" stroke-width="2" aria-hidden="true">
            <path d="M12 2a10 10 0 100 20A10 10 0 0012 2z"/>
            <path d="M12 6v6l4 2"/>
          </svg>
        </div>
        <div class="info-card-title">Adaptação Metab?lica</div>
        <div class="info-card-desc">
          A projeção modela a <span class="info-card-highlight">desaceleração natural</span> do metabolismo em resposta ao déficit. 
          Nas semanas 4?8, a curva — mais suave — o corpo adapta até <span class="info-card-highlight">~35%</span> do TDEE original.
        </div>
        <div class="adaptation-bar-wrap" role="group" aria-label="Barra de adaptação metabólica">
          <div class="adaptation-bar-header">
            <span>Adaptação atual</span>
            <span style="color:var(--color-amber);font-weight:700;">~35%</span>
          </div>
          <div class="adaptation-bar-track" aria-hidden="true">
            <div class="adaptation-bar-fill" id="adaptationBar" role="progressbar" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100" aria-label="35% de adaptação metabólica"></div>
          </div>
        </div>
      </div>

      <!-- REFEEDS PROGRAMADOS -->
      <div class="info-card animate-fade-up delay-7" role="complementary" aria-label="Informação sobre refeeds programados">
        <div class="info-card-icon-wrap" style="background:var(--color-amber-muted)" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-amber)" stroke-width="2" aria-hidden="true">
            <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/>
            <circle cx="9" cy="7" r="4"/>
            <path d="M23 21v-2a4 4 0 00-3-3.87"/>
            <path d="M16 3.13a4 4 0 010 7.75"/>
          </svg>
        </div>
        <div class="info-card-title">Refeeds Estratégicos</div>
        <div class="info-card-desc">
          4 dias de recarga programados para <span class="info-card-highlight">resetar leptina</span>, 
          manter performance e prevenir catabolismo muscular. S?o <em>parte do protocolo</em>, não trapa?as.
        </div>
        <div class="refeed-schedule" role="list" aria-label="Calend?rio de refeeds">
          <div class="refeed-item" role="listitem" aria-label="Refeed na semana 4">
            <span class="refeed-item-week">Semana 4</span>
            <span class="refeed-item-desc">1? ciclo — Leptina</span>
            <span class="refeed-item-badge">+400 kcal</span>
          </div>
          <div class="refeed-item" role="listitem" aria-label="Refeed na semana 8">
            <span class="refeed-item-week">Semana 8</span>
            <span class="refeed-item-desc">2? ciclo — Metab?lico</span>
            <span class="refeed-item-badge">+400 kcal</span>
          </div>
          <div class="refeed-item" role="listitem" aria-label="Refeed na semana 12">
            <span class="refeed-item-week">Semana 12</span>
            <span class="refeed-item-desc">3? ciclo — Performance</span>
            <span class="refeed-item-badge">+400 kcal</span>
          </div>
          <div class="refeed-item" role="listitem" aria-label="Refeed na semana 15">
            <span class="refeed-item-week">Semana 15</span>
            <span class="refeed-item-desc">4? ciclo — Final sprint</span>
            <span class="refeed-item-badge">+400 kcal</span>
          </div>
        </div>
      </div>

      <!-- VELOCIDADE & CLASSIFICAÃ‡ÃƒO -->
      <div class="info-card animate-fade-up delay-8" role="complementary" aria-label="Velocidade e classificação do protocolo">
        <div class="info-card-icon-wrap" style="background:rgba(59,130,246,0.1)" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="var(--color-blue)" stroke-width="2" aria-hidden="true">
            <path d="M22 12h-4l-3 9L9 3l-3 9H2"/>
          </svg>
        </div>
        <div class="info-card-title">Velocidade &amp; Classificação</div>
        <div class="info-card-desc">
          Perda m?dia de <span class="info-card-highlight">~0.53 kg/semana</span> — dentro da janela ideal de 
          <span class="info-card-highlight">0.5–0.8% do peso corporal</span> por semana para retenção máxima de massa magra.
        </div>
        <div class="info-card-value-row" role="group" aria-label="Taxa de perda: 0.63% do peso por semana">
          <span class="info-card-big-value" style="color:var(--color-blue)">0.63</span>
          <span class="info-card-big-unit">% peso/semana</span>
        </div>
        <div style="margin-top:var(--space-2);display:flex;gap:var(--space-2);flex-wrap:wrap;">
          <span class="milestone-tag teal" style="font-size:10px">Zona Ideal</span>
          <span class="milestone-tag red" style="font-size:10px">Anti-Catab?lico</span>
          <span class="milestone-tag purple" style="font-size:10px">Sustent?vel</span>
        </div>
      </div>

    </div>

    <!-- ============================================= -->
    <!-- WEEKLY BREAKDOWN TABLE                      -->
    <!-- ============================================= -->
    <section class="weekly-table-card animate-fade-up delay-8" aria-label="Tabela de progresso semanal detalhada">
      <div class="weekly-table-header">
        <div class="weekly-table-title">
          <div class="weekly-table-icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 000 4h6a2 2 0 000-4M9 5a2 2 0 012-2h2a2 2 0 012 2" stroke="var(--color-accent)" stroke-width="2"/>
            </svg>
          </div>
          Projeção Semana a Semana
        </div>
        <div class="table-toggle-wrap" role="group" aria-label="Selecionar visualização da tabela">
          <button class="table-toggle-btn active" id="btnAll" onclick="switchTableView('all')" aria-pressed="true">Todas</button>
          <button class="table-toggle-btn" id="btnHighlights" onclick="switchTableView('highlights')" aria-pressed="false">Marcos</button>
        </div>
      </div>
      <div class="weekly-table-scroll" role="region" aria-label="Tabela rol?vel" tabindex="0">
        <table class="weekly-table" id="weeklyTable" aria-label="Dados semanais de projeção corporal">
          <thead>
            <tr>
              <th scope="col">Semana</th>
              <th scope="col">Peso</th>
              <th scope="col">Î” Peso</th>
              <th scope="col">Body Fat %</th>
              <th scope="col">Massa Magra</th>
              <th scope="col">Gordura (kg)</th>
              <th scope="col">% do Objetivo</th>
              <th scope="col">Nota</th>
            </tr>
          </thead>
          <tbody id="weeklyTableBody">
            <!-- Preenchido por JS -->
          </tbody>
        </table>
      </div>
    </section>

    <!-- ============================================= -->
    <!-- DISCLAIMER                                  -->
    <!-- ============================================= -->
    <div class="projection-disclaimer animate-fade-up delay-9" role="note" aria-label="Aviso sobre a projeção">
      <div class="disclaimer-icon" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" stroke="var(--color-amber)" stroke-width="2"/>
          <line x1="12" y1="9" x2="12" y2="13" stroke="var(--color-amber)" stroke-width="2"/>
          <line x1="12" y1="17" x2="12.01" y2="17" stroke="var(--color-amber)" stroke-width="2"/>
        </svg>
      </div>
      <div class="disclaimer-text">
        <strong>Projeção baseada em modelo matemático com adaptação metabólica.</strong>
        Os valores s?o estimativas calculadas a partir do seu TDEE (2.487 kcal), déficit cal?rico (598 kcal/dia) 
        e dados de composição corporal inicial. A curva modela a desaceleração metabólica natural (adaptação termogênica de ~35% gradual). 
        Resultados reais variam conforme ader?ncia, qualidade do sono, estresse, treinamento e individualidade biol?gica. 
        Reavalie o protocolo a cada 4 semanas com medições reais.
      </div>
    </div>

    <!-- ============================================= -->
    <!-- SUMMARY FOOTER CTA                          -->
    <!-- ============================================= -->
    <footer class="summary-footer animate-fade-up delay-10" role="contentinfo" aria-label="Rodapé com resumo e ação">
      <div class="summary-footer-item" aria-label="Início do protocolo hoje">
        <div class="summary-footer-label">Início</div>
        <div class="summary-footer-value">Hoje</div>
        <div class="summary-footer-unit">dia 1/112</div>
      </div>
      <div class="summary-footer-divider" aria-hidden="true"></div>
      <div class="summary-footer-item" aria-label="Meta final: 75.5 kg">
        <div class="summary-footer-label">Meta</div>
        <div class="summary-footer-value" style="color:var(--color-teal)">75.5 kg</div>
        <div class="summary-footer-unit">em 16 semanas</div>
      </div>
      <div class="summary-footer-divider" aria-hidden="true"></div>
      <div class="summary-footer-item" aria-label="Body fat alvo: 8.7%">
        <div class="summary-footer-label">BF% alvo</div>
        <div class="summary-footer-value" style="color:var(--color-accent)">8.7%</div>
        <div class="summary-footer-unit">definição elite</div>
      </div>
      <div class="summary-footer-divider" aria-hidden="true"></div>
      <div class="summary-footer-item" aria-label="Calorias di?rias: 1889 kcal">
        <div class="summary-footer-label">Calorias/dia</div>
        <div class="summary-footer-value" style="color:var(--color-amber)">1.889</div>
        <div class="summary-footer-unit">kcal no protocolo</div>
      </div>
      <div class="summary-footer-divider" aria-hidden="true"></div>
      <div class="summary-footer-item" aria-label="Prote?na di?ria: 189g">
        <div class="summary-footer-label">Prote?na/dia</div>
        <div class="summary-footer-value" style="color:var(--color-purple)">189g</div>
        <div class="summary-footer-unit">2.24g / kg LBM</div>
      </div>
      <div class="summary-footer-divider" aria-hidden="true"></div>
      <button class="summary-footer-cta" onclick="triggerCelebration()" aria-label="Iniciar protocolo">
        <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5" aria-hidden="true">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        </svg>
        Iniciar Protocolo Agora
      </button>
    </footer>

  </div><!-- /page-wrapper -->

  <!-- ============================================= -->
  <!-- JAVASCRIPT — LÃ“GICA COMPLETA                 -->
  <!-- ============================================= -->`;

export const LEGACY_PROJECTION_SCRIPT = `'use strict';

    // =============================================
    // SEÃ‡ÃƒO: DADOS DO PROTOCOLO
    // =============================================

    const PROTOCOL = {
      startWeight:  84.0,
      endWeight:    75.5,
      startBf:      18.0,
      endBf:        8.7,
      startLbm:     68.88,
      endLbm:       68.9,
      weeks:        16,
      deficitKcal:  598,
      refeedWeeks:  [4, 8, 12, 15],
      tdee:         2487,
      calories:     1889,
    };

    // =============================================
    // SEÃ‡ÃƒO: GERAÃ‡ÃƒO DOS DADOS SEMANAIS
    //  Modela: adaptação metabólica (curva de 
    //  desaceleração), micro-flutuações orgânicas,
    //  e dias de refeed com bounce.
    // =============================================

    function generateWeeklyData() {
      const data = [];
      const { startWeight, endWeight, startBf, endBf, startLbm, weeks, refeedWeeks } = PROTOCOL;
      const totalLoss = startWeight - endWeight;
      const totalBfDrop = startBf - endBf;

      // Função de progressão não-linear (adaptação metabólica)
      // Início rápido ? progressivo desaceleramento ? stabilização final
      function adaptedProgress(week) {
        const t = week / weeks;
        // Curva: in?cio mais rápido, desacelera na metade, recupera no final
        const base = t < 0.5
          ? 2 * t * t * (1 + 0.3 * t)
          : 1 - 2 * (1 - t) * (1 - t) * (1 + 0.15 * (1 - t));
        return Math.min(1, Math.max(0, base));
      }

      // Gera flutuação org?nica (pseudo-random determin?stica)
      function organicNoise(week, seed) {
        const s = Math.sin(week * 2.37 + seed * 5.1) * 0.5 + 0.5;
        const s2 = Math.sin(week * 0.9 + seed * 3.7) * 0.5 + 0.5;
        return (s * 0.7 + s2 * 0.3 - 0.5) * 0.22;
      }

      for (let w = 0; w <= weeks; w++) {
        const isRefeed = refeedWeeks.includes(w);
        const progress = adaptedProgress(w);
        const noise = w > 0 ? organicNoise(w, 42) : 0;

        // Peso: progressão não-linear + ru?do org?nico + bounce em refeed
        const refeedBounce = isRefeed ? 0.12 : 0;
        const weight = parseFloat(
          (startWeight - totalLoss * progress + noise * 0.3 + refeedBounce).toFixed(2)
        );

        // BF%: cai proporcionalmente mas um pouco mais rápido no in?cio
        const bfProgress = adaptedProgress(w) * (1 + 0.05 * (1 - w / weeks));
        const bf = parseFloat(
          Math.max(endBf, startBf - totalBfDrop * Math.min(1, bfProgress)).toFixed(1)
        );

        // LBM: marginalmente preservada (protocolo anti-catab?lico)
        const lbm = parseFloat(Math.max(startLbm - 0.1, weight * (1 - bf / 100)).toFixed(2));

        // Gordura em kg
        const fatKg = parseFloat((weight * bf / 100).toFixed(2));

        // Delta de peso em relação ? semana anterior
        const delta = w === 0 ? 0 : parseFloat((weight - data[w - 1].weight).toFixed(2));

        data.push({
          week: w,
          weight,
          bf,
          lbm,
          fatKg,
          delta,
          isRefeed,
          progressPct: Math.round(progress * 100),
        });
      }
      return data;
    }

    const WEEKLY_DATA = generateWeeklyData();

    // =============================================
    // SEÃ‡ÃƒO: ESTADO DA UI
    // =============================================
    const state = {
      visibleSeries: { weight: true, bf: true, lbm: true },
      hoveredWeek: null,
      selectedWeek: null,
      tableView: 'all',
      animationStarted: false,
      chartAnimProgress: 0.16,
      chartAnimFrame: null,
    };

    // =============================================
    // SEÃ‡ÃƒO: CANVAS CHART ? ENGINE COMPLETA
    // =============================================

    const canvas = document.getElementById('projectionChart');
    const ctx = canvas.getContext('2d');

    // Dimens?es responsivas
    function resizeCanvas() {
      const wrapper = canvas.parentElement;
      const dpr = window.devicePixelRatio || 1;
      const w = wrapper.clientWidth;
      const h = wrapper.clientHeight;
      canvas.width = w * dpr;
      canvas.height = h * dpr;
      canvas.style.width = w + 'px';
      canvas.style.height = h + 'px';
      ctx.scale(dpr, dpr);
    }

    // Padding do gr?fico
    const PAD = { top: 24, right: 48, bottom: 56, left: 68 };

    function getChartDims() {
      const dpr = window.devicePixelRatio || 1;
      const w = canvas.width / dpr;
      const h = canvas.height / dpr;
      return {
        w, h,
        innerW: w - PAD.left - PAD.right,
        innerH: h - PAD.top - PAD.bottom,
      };
    }

    // Mapeamento de valor para coordenada X
    function xForWeek(week, dims) {
      return PAD.left + (week / PROTOCOL.weeks) * dims.innerW;
    }

    // Mapeamento de valor de peso para Y
    const WEIGHT_MIN = 73;
    const WEIGHT_MAX = 86;
    function yForWeight(val, dims) {
      const norm = (val - WEIGHT_MIN) / (WEIGHT_MAX - WEIGHT_MIN);
      return PAD.top + dims.innerH - norm * dims.innerH;
    }

    // Mapeamento de valor de BF% para Y
    const BF_MIN = 6;
    const BF_MAX = 21;
    function yForBf(val, dims) {
      const norm = (val - BF_MIN) / (BF_MAX - BF_MIN);
      return PAD.top + dims.innerH - norm * dims.innerH;
    }

    // Mapeamento de LBM para Y (escala separada visual ? normalizada para caber)
    const LBM_MIN = 66;
    const LBM_MAX = 72;
    function yForLbm(val, dims) {
      const norm = (val - LBM_MIN) / (LBM_MAX - LBM_MIN);
      return PAD.top + dims.innerH - norm * dims.innerH;
    }

    // =============================================
    // SEÃ‡ÃƒO: RENDER DO CANVAS ? FRAME COMPLETO
    // =============================================

    function renderChart(animProgress = 1) {
      resizeCanvas();
      const dims = getChartDims();
      const { w, h, innerW, innerH } = dims;

      // Limpa
      ctx.clearRect(0, 0, w, h);

      // ---- BACKGROUND ----
      const bgGrad = ctx.createLinearGradient(0, 0, 0, h);
      bgGrad.addColorStop(0, 'rgba(19, 19, 31, 0)');
      bgGrad.addColorStop(1, 'rgba(10, 10, 15, 0)');
      ctx.fillStyle = bgGrad;
      ctx.fillRect(0, 0, w, h);

      // ---- GRID HORIZONTAL ----
      const gridLinesY = 6;
      for (let i = 0; i <= gridLinesY; i++) {
        const y = PAD.top + (i / gridLinesY) * innerH;
        ctx.beginPath();
        ctx.moveTo(PAD.left, y);
        ctx.lineTo(PAD.left + innerW, y);
        ctx.strokeStyle = i === gridLinesY
          ? 'rgba(255,255,255,0.08)'
          : 'rgba(255,255,255,0.04)';
        ctx.lineWidth = 1;
        ctx.setLineDash([]);
        ctx.stroke();
      }

      // ---- GRID VERTICAL (semanas) ----
      for (let w2 = 0; w2 <= PROTOCOL.weeks; w2++) {
        const x = xForWeek(w2, dims);
        const isRefeed = PROTOCOL.refeedWeeks.includes(w2);
        ctx.beginPath();
        ctx.moveTo(x, PAD.top);
        ctx.lineTo(x, PAD.top + innerH);
        if (isRefeed) {
          ctx.strokeStyle = 'rgba(245,158,11,0.12)';
          ctx.lineWidth = 1.5;
          ctx.setLineDash([3, 4]);
        } else {
          ctx.strokeStyle = 'rgba(255,255,255,0.025)';
          ctx.lineWidth = 1;
          ctx.setLineDash([]);
        }
        ctx.stroke();
        ctx.setLineDash([]);
      }

      // ---- REFEED WEEK BANDS ----
      PROTOCOL.refeedWeeks.forEach(rw => {
        const x = xForWeek(rw, dims);
        const bw = (innerW / PROTOCOL.weeks) * 0.6;
        const refeedGrad = ctx.createLinearGradient(x - bw / 2, 0, x + bw / 2, 0);
        refeedGrad.addColorStop(0, 'transparent');
        refeedGrad.addColorStop(0.5, 'rgba(245,158,11,0.04)');
        refeedGrad.addColorStop(1, 'transparent');
        ctx.fillStyle = refeedGrad;
        ctx.fillRect(x - bw / 2, PAD.top, bw, innerH);

        // Label "REFEED"
        ctx.font = '600 9px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(245,158,11,0.5)';
        ctx.letterSpacing = '0.08em';
        ctx.textAlign = 'center';
        ctx.fillText('REFEED', x, PAD.top - 6);
        ctx.letterSpacing = '0';
      });

      // ---- AXIS LABELS LEFT ? PESO (kg) ----
      const weightRange = WEIGHT_MAX - WEIGHT_MIN;
      for (let i = 0; i <= gridLinesY; i++) {
        const val = WEIGHT_MIN + (i / gridLinesY) * weightRange;
        const y = PAD.top + innerH - (i / gridLinesY) * innerH;
        ctx.font = '11px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(16,185,129,0.6)';
        ctx.textAlign = 'right';
        ctx.fillText(val.toFixed(0) + 'kg', PAD.left - 10, y + 4);
      }

      // ---- AXIS LABELS RIGHT ? BF% ----
      const bfRange = BF_MAX - BF_MIN;
      for (let i = 0; i <= gridLinesY; i++) {
        const val = BF_MIN + (i / gridLinesY) * bfRange;
        const y = PAD.top + innerH - (i / gridLinesY) * innerH;
        ctx.font = '11px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(45,212,191,0.5)';
        ctx.textAlign = 'left';
        ctx.fillText(val.toFixed(0) + '%', PAD.left + innerW + 8, y + 4);
      }

      // ---- AXIS LABELS BOTTOM ? SEMANAS ----
      for (let w2 = 0; w2 <= PROTOCOL.weeks; w2 += 2) {
        const x = xForWeek(w2, dims);
        ctx.font = '11px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(148,163,184,0.6)';
        ctx.textAlign = 'center';
        ctx.fillText(w2 === 0 ? 'Início' : \`S\${w2}\`, x, PAD.top + innerH + 18);
      }

      // ---- AXIS TITLES ----
      ctx.save();
      ctx.font = '700 10px -apple-system, system-ui, sans-serif';
      ctx.fillStyle = 'rgba(16,185,129,0.5)';
      ctx.textAlign = 'center';
      ctx.translate(14, PAD.top + innerH / 2);
      ctx.rotate(-Math.PI / 2);
      ctx.fillText('PESO (kg)', 0, 0);
      ctx.restore();

      ctx.save();
      ctx.font = '700 10px -apple-system, system-ui, sans-serif';
      ctx.fillStyle = 'rgba(45,212,191,0.5)';
      ctx.textAlign = 'center';
      ctx.translate(w - 10, PAD.top + innerH / 2);
      ctx.rotate(Math.PI / 2);
      ctx.fillText('BF%', 0, 0);
      ctx.restore();

      // ---- C?LCULO DOS PONTOS ANIMADOS ----
      // animProgress vai de 0 a 1 ? s? mostra até o ponto animado
      const maxWeekAnim = Math.floor(animProgress * PROTOCOL.weeks);
      const fracWeek = (animProgress * PROTOCOL.weeks) - maxWeekAnim;

      function getAnimatedPoints(yFn) {
        const pts = [];
        for (let i = 0; i <= maxWeekAnim && i < WEEKLY_DATA.length; i++) {
          const d = WEEKLY_DATA[i];
          pts.push({ x: xForWeek(d.week, dims), y: yFn(d, dims) });
        }
        // Interpolação do ?ltimo ponto parcial
        if (maxWeekAnim < PROTOCOL.weeks && maxWeekAnim + 1 < WEEKLY_DATA.length && fracWeek > 0) {
          const d0 = WEEKLY_DATA[maxWeekAnim];
          const d1 = WEEKLY_DATA[maxWeekAnim + 1];
          const interpX = xForWeek(d0.week + fracWeek, dims);
          const interpY = yFn(d0, dims) + (yFn(d1, dims) - yFn(d0, dims)) * fracWeek;
          pts.push({ x: interpX, y: interpY });
        }
        return pts;
      }

      // ---- SÃ‰RIE: MASSA MAGRA (LBM) ----
      if (state.visibleSeries.lbm) {
        const pts = getAnimatedPoints((d) => yForLbm(d.lbm, dims));
        if (pts.length >= 2) {
          // ?rea preenchida
          ctx.beginPath();
          ctx.moveTo(pts[0].x, PAD.top + innerH);
          pts.forEach(p => ctx.lineTo(p.x, p.y));
          ctx.lineTo(pts[pts.length - 1].x, PAD.top + innerH);
          ctx.closePath();
          const lbmFill = ctx.createLinearGradient(0, PAD.top, 0, PAD.top + innerH);
          lbmFill.addColorStop(0, 'rgba(168,85,247,0.10)');
          lbmFill.addColorStop(1, 'rgba(168,85,247,0.01)');
          ctx.fillStyle = lbmFill;
          ctx.fill();

          // Linha suave
          ctx.beginPath();
          drawSmoothLine(ctx, pts);
          ctx.strokeStyle = 'rgba(168,85,247,0.55)';
          ctx.lineWidth = 2;
          ctx.setLineDash([6, 4]);
          ctx.stroke();
          ctx.setLineDash([]);
        }
      }

      // ---- SÃ‰RIE: BODY FAT % ----
      if (state.visibleSeries.bf) {
        const pts = getAnimatedPoints((d) => yForBf(d.bf, dims));
        if (pts.length >= 2) {
          // ?rea preenchida
          ctx.beginPath();
          ctx.moveTo(pts[0].x, PAD.top + innerH);
          pts.forEach(p => ctx.lineTo(p.x, p.y));
          ctx.lineTo(pts[pts.length - 1].x, PAD.top + innerH);
          ctx.closePath();
          const bfFill = ctx.createLinearGradient(0, PAD.top, 0, PAD.top + innerH);
          bfFill.addColorStop(0, 'rgba(45,212,191,0.18)');
          bfFill.addColorStop(0.6, 'rgba(45,212,191,0.06)');
          bfFill.addColorStop(1, 'rgba(45,212,191,0.01)');
          ctx.fillStyle = bfFill;
          ctx.fill();

          // Linha
          ctx.beginPath();
          drawSmoothLine(ctx, pts);
          ctx.strokeStyle = 'rgba(45,212,191,0.85)';
          ctx.lineWidth = 2.5;
          ctx.setLineDash([]);
          ctx.stroke();
        }
      }

      // ---- SÃ‰RIE: PESO CORPORAL ----
      if (state.visibleSeries.weight) {
        const pts = getAnimatedPoints((d) => yForWeight(d.weight, dims));
        if (pts.length >= 2) {
          // ?rea preenchida com gradiente
          ctx.beginPath();
          ctx.moveTo(pts[0].x, PAD.top + innerH);
          pts.forEach(p => ctx.lineTo(p.x, p.y));
          ctx.lineTo(pts[pts.length - 1].x, PAD.top + innerH);
          ctx.closePath();
          const weightFill = ctx.createLinearGradient(0, PAD.top, 0, PAD.top + innerH);
          weightFill.addColorStop(0, 'rgba(16,185,129,0.28)');
          weightFill.addColorStop(0.4, 'rgba(16,185,129,0.12)');
          weightFill.addColorStop(1, 'rgba(16,185,129,0.01)');
          ctx.fillStyle = weightFill;
          ctx.fill();

          // GLOW linha (camada de glow mais larga)
          ctx.beginPath();
          drawSmoothLine(ctx, pts);
          ctx.strokeStyle = 'rgba(16,185,129,0.2)';
          ctx.lineWidth = 8;
          ctx.setLineDash([]);
          ctx.shadowBlur = 12;
          ctx.shadowColor = 'rgba(16,185,129,0.4)';
          ctx.stroke();
          ctx.shadowBlur = 0;

          // Linha principal
          ctx.beginPath();
          drawSmoothLine(ctx, pts);
          ctx.strokeStyle = 'rgba(16,185,129,1)';
          ctx.lineWidth = 2.5;
          ctx.setLineDash([]);
          ctx.stroke();
        }
      }

      // ---- PONTOS DE DADO + REFEEDS ----
      if (animProgress >= 0.05) {
        for (let i = 0; i <= Math.min(maxWeekAnim, PROTOCOL.weeks); i++) {
          if (i >= WEEKLY_DATA.length) break;
          const d = WEEKLY_DATA[i];
          const xp = xForWeek(d.week, dims);
          const isHovered = state.hoveredWeek === d.week;
          const isSelected = state.selectedWeek === d.week;
          const isRefeed = d.isRefeed;

          // ---- PONTOS DE PESO ----
          if (state.visibleSeries.weight) {
            const yp = yForWeight(d.weight, dims);
            const r = isHovered || isSelected ? 6 : (isRefeed ? 5 : 3.5);

            if (isHovered || isSelected) {
              ctx.beginPath();
              ctx.arc(xp, yp, r + 5, 0, Math.PI * 2);
              ctx.fillStyle = 'rgba(16,185,129,0.12)';
              ctx.fill();
            }

            ctx.beginPath();
            ctx.arc(xp, yp, r, 0, Math.PI * 2);
            ctx.fillStyle = isRefeed ? 'rgba(245,158,11,0.9)' : 'rgba(16,185,129,0.95)';
            ctx.shadowBlur = isHovered ? 15 : 6;
            ctx.shadowColor = isRefeed ? 'rgba(245,158,11,0.6)' : 'rgba(16,185,129,0.6)';
            ctx.fill();
            ctx.shadowBlur = 0;

            // Annel branco
            ctx.beginPath();
            ctx.arc(xp, yp, r, 0, Math.PI * 2);
            ctx.strokeStyle = isHovered ? 'rgba(255,255,255,0.9)' : 'rgba(255,255,255,0.5)';
            ctx.lineWidth = 1.5;
            ctx.stroke();
          }

          // ---- PONTOS DE BF% ----
          if (state.visibleSeries.bf) {
            const yb = yForBf(d.bf, dims);
            const r = isHovered || isSelected ? 5 : 3;

            if (isHovered || isSelected) {
              ctx.beginPath();
              ctx.arc(xp, yb, r + 4, 0, Math.PI * 2);
              ctx.fillStyle = 'rgba(45,212,191,0.1)';
              ctx.fill();
            }

            ctx.beginPath();
            ctx.arc(xp, yb, r, 0, Math.PI * 2);
            ctx.fillStyle = 'rgba(45,212,191,0.9)';
            ctx.shadowBlur = isHovered ? 12 : 4;
            ctx.shadowColor = 'rgba(45,212,191,0.5)';
            ctx.fill();
            ctx.shadowBlur = 0;

            ctx.beginPath();
            ctx.arc(xp, yb, r, 0, Math.PI * 2);
            ctx.strokeStyle = isHovered ? 'rgba(255,255,255,0.9)' : 'rgba(255,255,255,0.4)';
            ctx.lineWidth = 1;
            ctx.stroke();
          }

          // ---- PONTOS DE LBM ----
          if (state.visibleSeries.lbm && (isHovered || isSelected || i % 4 === 0)) {
            const yl = yForLbm(d.lbm, dims);
            const r = isHovered || isSelected ? 4 : 2.5;

            ctx.beginPath();
            ctx.arc(xp, yl, r, 0, Math.PI * 2);
            ctx.fillStyle = 'rgba(168,85,247,0.85)';
            ctx.fill();
            ctx.strokeStyle = 'rgba(255,255,255,0.3)';
            ctx.lineWidth = 1;
            ctx.stroke();
          }

          // ---- REFEED VERTICAL LINE ----
          if (isRefeed) {
            ctx.beginPath();
            ctx.moveTo(xp, PAD.top + 4);
            ctx.lineTo(xp, PAD.top + innerH);
            ctx.strokeStyle = 'rgba(245,158,11,0.35)';
            ctx.lineWidth = 1;
            ctx.setLineDash([2, 3]);
            ctx.stroke();
            ctx.setLineDash([]);

            // Refeed diamond marker no topo da linha de peso
            if (state.visibleSeries.weight) {
              const yw = yForWeight(d.weight, dims);
              ctx.save();
              ctx.translate(xp, yw - 14);
              ctx.rotate(Math.PI / 4);
              ctx.beginPath();
              ctx.rect(-4, -4, 8, 8);
              ctx.fillStyle = 'rgba(245,158,11,0.9)';
              ctx.shadowBlur = 8;
              ctx.shadowColor = 'rgba(245,158,11,0.5)';
              ctx.fill();
              ctx.shadowBlur = 0;
              ctx.restore();
            }
          }

          // ---- HOVER VERTICAL LINE ----
          if (isHovered) {
            const topY = PAD.top;
            const botY = PAD.top + innerH;

            ctx.beginPath();
            ctx.moveTo(xp, topY);
            ctx.lineTo(xp, botY);
            ctx.strokeStyle = 'rgba(16,185,129,0.35)';
            ctx.lineWidth = 1;
            ctx.setLineDash([3, 3]);
            ctx.stroke();
            ctx.setLineDash([]);

            // Etiqueta de semana na linha
            const labelTxt = d.week === 0 ? 'Início' : \`Sem. \${d.week}\`;
            ctx.font = '700 11px -apple-system, system-ui, sans-serif';
            ctx.fillStyle = 'rgba(16,185,129,0.85)';
            ctx.textAlign = 'center';
            ctx.fillText(labelTxt, xp, PAD.top - 6);

            // Highlight nos eixos
            if (state.visibleSeries.weight) {
              const yw = yForWeight(d.weight, dims);
              ctx.font = '700 11px -apple-system, system-ui, sans-serif';
              ctx.fillStyle = 'rgba(16,185,129,0.9)';
              ctx.textAlign = 'right';
              ctx.fillText(d.weight.toFixed(1), PAD.left - 6, yw + 4);
            }
            if (state.visibleSeries.bf) {
              const yb = yForBf(d.bf, dims);
              ctx.font = '700 11px -apple-system, system-ui, sans-serif';
              ctx.fillStyle = 'rgba(45,212,191,0.9)';
              ctx.textAlign = 'left';
              ctx.fillText(d.bf.toFixed(1) + '%', PAD.left + innerW + 6, yb + 4);
            }
          }
        }
      }

      // ---- GOAL LINE (LINHA DE META) ----
      const goalX = xForWeek(PROTOCOL.weeks, dims);
      const goalYW = yForWeight(PROTOCOL.endWeight, dims);

      ctx.beginPath();
      ctx.moveTo(PAD.left, goalYW);
      ctx.lineTo(PAD.left + innerW, goalYW);
      ctx.strokeStyle = 'rgba(45,212,191,0.15)';
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 6]);
      ctx.stroke();
      ctx.setLineDash([]);

      // Goal label
      if (animProgress > 0.8) {
        const goalAlpha = Math.min(1, (animProgress - 0.8) / 0.2);
        ctx.font = \`700 10px -apple-system, system-ui, sans-serif\`;
        ctx.fillStyle = \`rgba(45,212,191,\${goalAlpha * 0.7})\`;
        ctx.textAlign = 'right';
        ctx.fillText(\`META: \${PROTOCOL.endWeight}kg\`, PAD.left + innerW - 6, goalYW - 6);
      }

      // ---- START ANNOTATION ----
      if (animProgress > 0) {
        const startX = xForWeek(0, dims);
        const startYW = yForWeight(PROTOCOL.startWeight, dims);
        ctx.font = '700 11px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(16,185,129,0.7)';
        ctx.textAlign = 'center';
        ctx.fillText(\`\${PROTOCOL.startWeight}kg\`, startX, startYW - 12);
      }

      // ---- END ANNOTATION ----
      if (animProgress >= 1) {
        const endX = xForWeek(PROTOCOL.weeks, dims);
        const endYW = yForWeight(WEEKLY_DATA[PROTOCOL.weeks].weight, dims);
        ctx.font = '700 11px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(45,212,191,0.9)';
        ctx.textAlign = 'center';
        ctx.fillText(\`~\${WEEKLY_DATA[PROTOCOL.weeks].weight}kg\`, endX, endYW - 12);

        const endYB = yForBf(WEEKLY_DATA[PROTOCOL.weeks].bf, dims);
        ctx.font = '700 10px -apple-system, system-ui, sans-serif';
        ctx.fillStyle = 'rgba(45,212,191,0.7)';
        ctx.fillText(\`\${WEEKLY_DATA[PROTOCOL.weeks].bf}%BF\`, endX, endYB + 18);
      }
    }

    // =============================================
    // SEÃ‡ÃƒO: HELPER ? LINHA SUAVE (Catmull-Rom)
    // =============================================
    function drawSmoothLine(ctx, points) {
      if (points.length < 2) return;
      ctx.moveTo(points[0].x, points[0].y);

      for (let i = 0; i < points.length - 1; i++) {
        const p0 = points[Math.max(0, i - 1)];
        const p1 = points[i];
        const p2 = points[Math.min(points.length - 1, i + 1)];
        const p3 = points[Math.min(points.length - 1, i + 2)];

        const tension = 0.45;
        const cp1x = p1.x + (p2.x - p0.x) * tension / 3;
        const cp1y = p1.y + (p2.y - p0.y) * tension / 3;
        const cp2x = p2.x - (p3.x - p1.x) * tension / 3;
        const cp2y = p2.y - (p3.y - p1.y) * tension / 3;

        ctx.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, p2.x, p2.y);
      }
    }

    // =============================================
    // SEÃ‡ÃƒO: ANIMAÃ‡ÃƒO DE ENTRADA DO GR?FICO
    // =============================================
    function startChartAnimation() {
      if (state.animationStarted) return;
      state.animationStarted = true;

      const duration = 2800; // ms
      const startTime = performance.now();
      const initialProgress = Math.max(0, Math.min(1, state.chartAnimProgress || 0));

      function easeInOutCubic(t) {
        return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
      }

      function frame(now) {
        const elapsed = now - startTime;
        const raw = Math.min(1, elapsed / duration);
        state.chartAnimProgress = initialProgress + (1 - initialProgress) * easeInOutCubic(raw);
        renderChart(state.chartAnimProgress);
        if (raw < 1) {
          state.chartAnimFrame = requestAnimationFrame(frame);
        } else {
          state.chartAnimProgress = 1;
          renderChart(1);
        }
      }
      state.chartAnimFrame = requestAnimationFrame(frame);
    }

    // =============================================
    // SEÃ‡ÃƒO: INTERSECTION OBSERVER ? GATILHO
    // =============================================
    const chartObserver = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !state.animationStarted) {
          setTimeout(startChartAnimation, 200);
          animateStackedBars();
          animateAdaptationBar();
          animateCounterStats();
        }
      });
    }, { threshold: 0.1 });

    if (canvas) {
      chartObserver.observe(canvas);
    }
    setTimeout(() => {
      if (!state.animationStarted) {
        startChartAnimation();
        animateStackedBars();
        animateAdaptationBar();
        animateCounterStats();
      }
    }, 120);

    // =============================================
    // SEÃ‡ÃƒO: INTERAÃ‡ÃƒO ? MOUSE HOVER NO CANVAS
    // =============================================
    canvas.addEventListener('mousemove', (e) => {
      if (state.chartAnimProgress < 0.3) return;

      const rect = canvas.getBoundingClientRect();
      const mx = e.clientX - rect.left;
      const dims = getChartDims();

      // Encontra a semana mais pr?xima
      let closestWeek = null;
      let closestDist = Infinity;
      const maxWeek = Math.floor(state.chartAnimProgress * PROTOCOL.weeks);

      for (let w2 = 0; w2 <= maxWeek; w2++) {
        const x = xForWeek(w2, dims);
        const dist = Math.abs(mx - x);
        if (dist < closestDist) {
          closestDist = dist;
          closestWeek = w2;
        }
      }

      const threshold = (dims.innerW / PROTOCOL.weeks) * 0.7;

      if (closestDist <= threshold && closestWeek !== null) {
        if (state.hoveredWeek !== closestWeek) {
          state.hoveredWeek = closestWeek;
          renderChart(state.chartAnimProgress);
          showTooltip(e.clientX, e.clientY, WEEKLY_DATA[closestWeek]);
          updateWeekPill(closestWeek);
        }
      } else {
        if (state.hoveredWeek !== null) {
          state.hoveredWeek = null;
          renderChart(state.chartAnimProgress);
          hideTooltip();
        }
      }
    });

    canvas.addEventListener('mouseleave', () => {
      state.hoveredWeek = null;
      renderChart(state.chartAnimProgress);
      hideTooltip();
    });

    canvas.addEventListener('click', (e) => {
      if (state.hoveredWeek !== null) {
        state.selectedWeek = state.selectedWeek === state.hoveredWeek ? null : state.hoveredWeek;
        renderChart(state.chartAnimProgress);
        if (state.selectedWeek !== null) {
          scrollToTableRow(state.selectedWeek);
          highlightWeek(state.selectedWeek);
        }
      }
    });

    canvas.addEventListener('touchmove', (e) => {
      e.preventDefault();
      const touch = e.touches[0];
      const rect = canvas.getBoundingClientRect();
      const mx = touch.clientX - rect.left;
      const dims = getChartDims();

      let closestWeek = null;
      let closestDist = Infinity;
      const maxWeek = Math.floor(state.chartAnimProgress * PROTOCOL.weeks);

      for (let w2 = 0; w2 <= maxWeek; w2++) {
        const x = xForWeek(w2, dims);
        const dist = Math.abs(mx - x);
        if (dist < closestDist) {
          closestDist = dist;
          closestWeek = w2;
        }
      }

      if (closestWeek !== null && state.hoveredWeek !== closestWeek) {
        state.hoveredWeek = closestWeek;
        renderChart(state.chartAnimProgress);
        showTooltip(touch.clientX, touch.clientY, WEEKLY_DATA[closestWeek]);
        updateWeekPill(closestWeek);
      }
    }, { passive: false });

    canvas.addEventListener('touchend', () => {
      state.hoveredWeek = null;
      renderChart(state.chartAnimProgress);
      hideTooltip();
    });

    // =============================================
    // SEÃ‡ÃƒO: TOOLTIP SHOW/HIDE
    // =============================================
    const tooltip = document.getElementById('chartTooltip');
    const tooltipWeekBadge = document.getElementById('tooltipWeekBadge');
    const tooltipRefeedFlag = document.getElementById('tooltipRefeedFlag');
    const tooltipRows = document.getElementById('tooltipRows');
    const tooltipProgressPct = document.getElementById('tooltipProgressPct');
    const tooltipProgressFill = document.getElementById('tooltipProgressFill');

    function showTooltip(clientX, clientY, d) {
      const weekLabel = d.week === 0 ? 'Semana Inicial' : \`Semana \${d.week} de \${PROTOCOL.weeks}\`;
      tooltipWeekBadge.textContent = d.week === 0 ? 'Início' : \`Sem. \${d.week}\`;

      if (d.isRefeed) {
        tooltipRefeedFlag.innerHTML = '<span class="tooltip-refeed-flag">? Refeed Day</span>';
      } else {
        tooltipRefeedFlag.innerHTML = '';
      }

      const weightDelta = d.delta !== 0 ? d.delta.toFixed(2) : null;
      const bfDelta = d.week > 0
        ? (d.bf - WEEKLY_DATA[d.week - 1].bf).toFixed(1)
        : null;

      tooltipRows.innerHTML = \`
        <div class="tooltip-row">
          <span class="tooltip-row-label">
            <span class="tooltip-row-dot" style="background:var(--color-accent)"></span>
            Peso
          </span>
          <span>
            <span class="tooltip-row-value">\${d.weight.toFixed(2)} kg</span>
            \${weightDelta ? \`<span class="tooltip-row-delta negative">\${weightDelta > 0 ? '+' : ''}\${weightDelta} kg</span>\` : ''}
          </span>
        </div>
        <div class="tooltip-row">
          <span class="tooltip-row-label">
            <span class="tooltip-row-dot" style="background:var(--color-teal)"></span>
            Body Fat
          </span>
          <span>
            <span class="tooltip-row-value">\${d.bf.toFixed(1)}%</span>
            \${bfDelta ? \`<span class="tooltip-row-delta negative">\${parseFloat(bfDelta) > 0 ? '+' : ''}\${bfDelta}%</span>\` : ''}
          </span>
        </div>
        <div class="tooltip-row">
          <span class="tooltip-row-label">
            <span class="tooltip-row-dot" style="background:var(--color-purple)"></span>
            Massa Magra
          </span>
          <span class="tooltip-row-value">\${d.lbm.toFixed(2)} kg</span>
        </div>
        <div class="tooltip-divider"></div>
        <div class="tooltip-row">
          <span class="tooltip-row-label" style="color:var(--text-tertiary)">Gordura</span>
          <span class="tooltip-row-value" style="color:var(--text-secondary)">\${d.fatKg.toFixed(2)} kg</span>
        </div>
        \${d.week > 0 ? \`
        <div class="tooltip-row">
          <span class="tooltip-row-label" style="color:var(--text-tertiary)">Perda acumulada</span>
          <span class="tooltip-row-value" style="color:#22c55e">\${(PROTOCOL.startWeight - d.weight).toFixed(2)} kg</span>
        </div>\` : ''}
      \`;

      const progressPct = d.week > 0
        ? Math.round(((PROTOCOL.startWeight - d.weight) / (PROTOCOL.startWeight - PROTOCOL.endWeight)) * 100)
        : 0;
      tooltipProgressPct.textContent = \`\${progressPct}%\`;
      tooltipProgressFill.style.width = \`\${progressPct}%\`;

      // Posicionamento inteligente
      const ttW = 240;
      const ttH = 200;
      let left = clientX + 16;
      let top = clientY - ttH / 2;

      if (left + ttW > window.innerWidth - 20) {
        left = clientX - ttW - 16;
      }
      if (top < 10) top = 10;
      if (top + ttH > window.innerHeight - 10) top = window.innerHeight - ttH - 10;

      tooltip.style.left = left + 'px';
      tooltip.style.top = top + 'px';
      tooltip.classList.add('visible');
    }

    function hideTooltip() {
      tooltip.classList.remove('visible');
    }

    // =============================================
    // SEÃ‡ÃƒO: TOGGLE SÃ‰RIES DO GR?FICO
    // =============================================
    function toggleSeries(series) {
      state.visibleSeries[series] = !state.visibleSeries[series];

      const legendMap = { weight: 'legendWeight', bf: 'legendBF', lbm: 'legendLBM' };
      const el = document.getElementById(legendMap[series]);
      if (el) {
        el.classList.toggle('hidden-series', !state.visibleSeries[series]);
      }

      renderChart(state.chartAnimProgress);
    }

    // Suporte a teclado para legend items
    document.querySelectorAll('.legend-item').forEach(item => {
      item.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          item.click();
        }
      });
    });

    // =============================================
    // SEÃ‡ÃƒO: WEEK SELECTOR PILLS
    // =============================================
    function buildWeekPills() {
      const wrap = document.querySelector('.week-selector-wrap');
      if (!wrap) return;
      wrap.innerHTML = '';
      for (let w2 = 0; w2 <= PROTOCOL.weeks; w2++) {
        const isRefeed = PROTOCOL.refeedWeeks.includes(w2);
        const btn = document.createElement('button');
        btn.className = \`week-pill\${isRefeed ? ' refeed' : ''}\`;
        btn.textContent = w2 === 0 ? 'I' : w2;
        btn.setAttribute('aria-label', \`Semana \${w2}\${isRefeed ? ' ? Refeed' : ''}\`);
        btn.setAttribute('title', w2 === 0 ? 'Início' : \`Semana \${w2}\${isRefeed ? ' (Refeed)' : ''}\`);
        btn.onclick = () => {
          selectWeek(w2);
        };
        wrap.appendChild(btn);
      }
    }

    function selectWeek(week) {
      state.selectedWeek = week;
      state.hoveredWeek = week;
      renderChart(state.chartAnimProgress);
      showTooltip(
        window.innerWidth / 2,
        window.innerHeight / 2,
        WEEKLY_DATA[week]
      );
      updateWeekPill(week);
      scrollToTableRow(week);

      setTimeout(() => {
        state.hoveredWeek = null;
        renderChart(state.chartAnimProgress);
        hideTooltip();
      }, 2500);
    }

    function updateWeekPill(week) {
      document.querySelectorAll('.week-pill').forEach((btn, idx) => {
        btn.classList.toggle('active', idx === week);
      });
    }

    function highlightWeek(week) {
      selectWeek(week);
    }

    // =============================================
    // SEÃ‡ÃƒO: TABLE VIEW SWITCH
    // =============================================
    function switchTableView(view) {
      state.tableView = view;
      document.getElementById('btnAll').classList.toggle('active', view === 'all');
      document.getElementById('btnAll').setAttribute('aria-pressed', view === 'all');
      document.getElementById('btnHighlights').classList.toggle('active', view === 'highlights');
      document.getElementById('btnHighlights').setAttribute('aria-pressed', view === 'highlights');
      buildWeeklyTable();
    }

    // =============================================
    // SEÃ‡ÃƒO: TABELA SEMANAL ? BUILD COMPLETO
    // =============================================
    function buildWeeklyTable() {
      const tbody = document.getElementById('weeklyTableBody');
      tbody.innerHTML = '';

      const highlightWeeks = new Set([0, 1, 4, 6, 8, 10, 12, 14, 15, 16]);
      const data = state.tableView === 'highlights'
        ? WEEKLY_DATA.filter(d => highlightWeeks.has(d.week))
        : WEEKLY_DATA;

      data.forEach((d, idx) => {
        const isRefeed = d.isRefeed;
        const totalLoss = PROTOCOL.startWeight - d.weight;
        const progressPct = d.week > 0
          ? Math.round((totalLoss / (PROTOCOL.startWeight - PROTOCOL.endWeight)) * 100)
          : 0;

        const tr = document.createElement('tr');
        tr.className = isRefeed ? 'refeed-row' : (d.week === 0 ? 'current-row' : '');
        tr.setAttribute('tabindex', '0');
        tr.setAttribute('aria-label', \`Dados da semana \${d.week}\`);

        // Delay de animação escalonada
        tr.style.animationDelay = \`\${idx * 25}ms\`;

        const deltaColor = d.delta === 0 ? '' : (d.delta > 0 ? 'color:#34d399' : 'td-loss');
        const deltaText = d.delta === 0 ? '?' : \`\${d.delta > 0 ? '+' : ''}\${d.delta.toFixed(2)} kg\`;

        const noteContent = isRefeed
          ? \`<span class="refeed-badge-cell">? Refeed</span>\`
          : (d.week === 0
            ? '<span style="color:var(--color-accent);font-size:11px;font-weight:700">? Início</span>'
            : (d.week === PROTOCOL.weeks
              ? '<span style="color:var(--color-teal);font-size:11px;font-weight:700">? Meta</span>'
              : ''));

        tr.innerHTML = \`
          <td style="color:var(--text-primary);font-weight:700">
            \${d.week === 0 ? 'Início' : \`Semana \${d.week}\`}
          </td>
          <td class="td-weight">\${d.weight.toFixed(2)} kg</td>
          <td class="\${deltaColor}" style="font-weight:600;font-variant-numeric:tabular-nums">\${deltaText}</td>
          <td class="td-bf">\${d.bf.toFixed(1)}%</td>
          <td class="td-lbm">\${d.lbm.toFixed(2)} kg</td>
          <td style="color:var(--text-secondary);font-variant-numeric:tabular-nums">\${d.fatKg.toFixed(2)} kg</td>
          <td>
            <div class="progress-cell-wrap" aria-label="\${progressPct}% do objetivo">
              <div class="progress-cell-track" aria-hidden="true">
                <div class="progress-cell-fill" style="width:\${progressPct}%"></div>
              </div>
              <span style="font-size:12px;font-weight:700;color:var(--text-secondary);font-variant-numeric:tabular-nums">
                \${progressPct}%
              </span>
            </div>
          </td>
          <td>\${noteContent}</td>
        \`;

        tr.addEventListener('click', () => {
          selectWeek(d.week);
          tr.classList.add('shimmer-row');
          setTimeout(() => tr.classList.remove('shimmer-row'), 1500);
        });

        tr.addEventListener('keydown', (e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            tr.click();
          }
        });

        tbody.appendChild(tr);
      });
    }

    function scrollToTableRow(week) {
      const rows = document.querySelectorAll('#weeklyTableBody tr');
      rows.forEach((row, i) => {
        const weekCells = row.querySelectorAll('td');
        if (weekCells.length > 0) {
          const label = weekCells[0].textContent.trim();
          const rowWeek = label === 'Início' ? 0 : parseInt(label.replace('Semana ', ''));
          if (rowWeek === week) {
            row.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
            row.classList.add('shimmer-row');
            setTimeout(() => row.classList.remove('shimmer-row'), 1500);
          }
        }
      });
    }

    // =============================================
    // SEÃ‡ÃƒO: ANIMAÃ‡ÃƒO DAS BARRAS EMPILHADAS
    // =============================================
    function animateStackedBars() {
      const fills = document.querySelectorAll('.stacked-bar-fill');
      fills.forEach((fill, i) => {
        const targetWidth = fill.getAttribute('data-width') || '0%';
        setTimeout(() => {
          fill.style.width = targetWidth;
        }, i * 120);
      });
    }

    // =============================================
    // SEÃ‡ÃƒO: ANIMAÃ‡ÃƒO DA BARRA DE ADAPTAÃ‡ÃƒO
    // =============================================
    function animateAdaptationBar() {
      setTimeout(() => {
        const bar = document.getElementById('adaptationBar');
        if (bar) bar.classList.add('animated');
      }, 400);
    }

    // =============================================
    // SEÃ‡ÃƒO: COUNT-UP ANIMADO NOS STATS
    // =============================================
    function animateCounterStats() {
      function countUp(elementId, start, end, decimals, suffix, duration = 1600) {
        const el = document.getElementById(elementId);
        if (!el) return;
        const startTime = performance.now();
        const endVal = parseFloat(end);
        const startVal = parseFloat(start);
        const range = endVal - startVal;

        function easeOut(t) { return 1 - Math.pow(1 - t, 3); }

        function frame(now) {
          const elapsed = now - startTime;
          const progress = Math.min(1, elapsed / duration);
          const current = startVal + range * easeOut(progress);
          el.textContent = current.toFixed(decimals) + suffix;
          if (progress < 1) requestAnimationFrame(frame);
        }
        requestAnimationFrame(frame);
      }

      // Os stats de sum?rio fazem count-up
      countUp('statWeeks', 0, 16, 0, '');
      countUp('statLoss', 0, -8.5, 1, '', 2000);
      countUp('statDeficit', 0, 598, 0, '');
      countUp('statSpeed', 0, 0.53, 2, '~0.');
      // BF ? especial
      setTimeout(() => {
        const el = document.getElementById('statBf');
        if (el) {
          let val = 18.0;
          const target = 8.7;
          const dur = 1800;
          const startT = performance.now();
          function frameBf(now) {
            const t = Math.min(1, (now - startT) / dur);
            const ease = 1 - Math.pow(1 - t, 3);
            val = 18.0 - (18.0 - target) * ease;
            el.textContent = val.toFixed(1) + '%';
            if (t < 1) requestAnimationFrame(frameBf);
          }
          requestAnimationFrame(frameBf);
        }
      }, 300);

      // Corrige o statSpeed counter
      setTimeout(() => {
        const el = document.getElementById('statSpeed');
        if (el) {
          let val = 0;
          const target = 0.53;
          const dur = 1600;
          const startT = performance.now();
          function frameSpeed(now) {
            const t = Math.min(1, (now - startT) / dur);
            const ease = 1 - Math.pow(1 - t, 3);
            val = target * ease;
            el.textContent = '~' + val.toFixed(2);
            if (t < 1) requestAnimationFrame(frameSpeed);
          }
          requestAnimationFrame(frameSpeed);
        }
      }, 0);

      // E corrige o statLoss
      setTimeout(() => {
        const el = document.getElementById('statLoss');
        if (el) {
          let val = 0;
          const target = 8.5;
          const dur = 2000;
          const startT = performance.now();
          function frameLoss(now) {
            const t = Math.min(1, (now - startT) / dur);
            const ease = 1 - Math.pow(1 - t, 3);
            val = target * ease;
            el.textContent = '?' + val.toFixed(1);
            if (t < 1) requestAnimationFrame(frameLoss);
          }
          requestAnimationFrame(frameLoss);
        }
      }, 0);
    }

    // =============================================
    // SEÃ‡ÃƒO: CELEBRATION / CTA BUTTON
    // =============================================
    function triggerCelebration() {
      const overlay = document.getElementById('celebrateOverlay');
      overlay.classList.remove('show');
      void overlay.offsetWidth;
      overlay.classList.add('show');

      // Flash todos os summary stats
      document.querySelectorAll('.summary-stat').forEach((stat, i) => {
        setTimeout(() => {
          stat.style.transition = 'all 0.3s ease';
          stat.style.boxShadow = '0 0 30px rgba(45,212,191,0.2)';
          stat.style.borderColor = 'rgba(45,212,191,0.3)';
          setTimeout(() => {
            stat.style.boxShadow = '';
            stat.style.borderColor = '';
          }, 800);
        }, i * 80);
      });

      // Feedback visual no bot?o
      const btn = document.querySelector('.summary-footer-cta');
      if (btn) {
        const origText = btn.innerHTML;
        btn.innerHTML = \`
          <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5" aria-hidden="true">
            <polyline points="20,6 9,17 4,12"/>
          </svg>
          Protocolo Ativado!
        \`;
        btn.style.background = 'linear-gradient(135deg, #22c55e, #16a34a)';
        btn.style.boxShadow = '0 8px 30px rgba(34,197,94,0.4)';
        setTimeout(() => {
          btn.innerHTML = origText;
          btn.style.background = '';
          btn.style.boxShadow = '';
        }, 2500);
      }
    }

    // =============================================
    // SEÃ‡ÃƒO: RESIZE HANDLER (DEBOUNCED)
    // =============================================
    let resizeTimer = null;
    window.addEventListener('resize', () => {
      if (resizeTimer) clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        renderChart(state.chartAnimProgress);
      }, 80);
    });

    // =============================================
    // SEÃ‡ÃƒO: INICIALIZAÃ‡ÃƒO
    // =============================================
    function init() {
      // Build week pills
      buildWeekPills();

      // Build table
      buildWeeklyTable();

      // Initial render (static, sem animação)
      resizeCanvas();
      renderChart(state.chartAnimProgress);

      // Intersection observer para animações CSS
      const animObserver = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.style.animationPlayState = 'running';
          }
        });
      }, { threshold: 0.05 });

      document.querySelectorAll('.animate-fade-up, .animate-fade-left, .animate-fade-right').forEach(el => {
        el.style.animationPlayState = 'paused';
        animObserver.observe(el);
      });

      // Pausa inicial das animações CSS para controle manual
      document.querySelectorAll('[class*="animate-"]').forEach(el => {
        el.style.animationPlayState = 'running';
      });
    }

    // Aguarda DOM completo
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init);
    } else {
      init();
    }

    // =============================================
    // SEÃ‡ÃƒO: KEYBOARD NAVIGATION
    // =============================================
    document.addEventListener('keydown', (e) => {
      if (canvas && (document.activeElement === canvas || canvas.matches(':hover'))) {
        let week = state.selectedWeek !== null ? state.selectedWeek : 0;

        if (e.key === 'ArrowRight') {
          e.preventDefault();
          week = Math.min(PROTOCOL.weeks, week + 1);
          selectWeek(week);
        } else if (e.key === 'ArrowLeft') {
          e.preventDefault();
          week = Math.max(0, week - 1);
          selectWeek(week);
        } else if (e.key === 'Escape') {
          state.selectedWeek = null;
          state.hoveredWeek = null;
          renderChart(state.chartAnimProgress);
          hideTooltip();
        }
      }
    });`;
/* @deprecated Legacy projection payload kept temporarily for the final cleanup pass. */
