import type { FormData } from '@/lib/types';

import { initialFormData } from './formConfig';

export const exampleFormData: FormData = {
  ...initialFormData,
  goal: 'mini_cut',
  sex: 'male',
  age: 31,
  weightKg: 84,
  heightCm: 178,
  bodyFatMode: 'declared',
  bodyFatDeclaredPct: 18,
  activityLevel: 'moderate',
  trainingSessions: 4,
  trainingType: 'strength',
  trainingDurationMin: 65,
  cardioMode: 'both',
  stepsPerDay: 8500,
  cardioMinutesPerDay: 20,
  cardioModality: 'treadmill',
  cardioIntensity: 'moderate',
  hormonesEnabled: false,
  hormones: [],
  cyclePhase: 'middle',
  occupationType: 'mixed',
  deficitHistory: '1to3months',
  deficitSeverity: 'moderate',
  menstrualPhase: 'unknown',
  ethnicity: 'western',
  calibratedTdeeKcal: null,
  healthConditions: ['none'],
  thermogenic: 'caffeine',
  mealsPerDay: 4,
  fastedTraining: false,
  plantBasedStrict: false,
  goalMode: 'bf',
  targetWeightKg: null,
  targetBodyFatPct: 12,
  targetFatKg: null,
  targetWeeks: 16,
  bfDecision: null,
};
